### ISSUE TITLE
!!! Ф - Страница "Знание". Представление для текущего знания всех его предков, потомков и сестер в виде дерева 

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#100]
На странице "Знание" раздел "Связанные знания" необходимо заменить на дерево знаний.
 
![Дерево при просмотре знания - вер 5](https://user-images.githubusercontent.com/83456540/136664350-2696ac4e-5fb4-477e-9d12-3fc12acefc01.png)

1. В дерево выводится весь путь от корня до текущего знания (категории и знания), его сестры и все его потомки. 
2. Текущее знание выделяется цветом фона.
3.  Каждой вершине-знанию соответствует 2 иконки (1 - самого дерева; 2 - вид знания
4. Цвет фона иконок категорий тот же, что и у категорий в разделе  "Древо знаний".
5. Два цвета фона иконок знаний: голубой - основные знания; сиреневый - дополнительные зная 
6. Цвет фона Вида знаний: зеленоватый
7. Все иконки вершины имеют один цвет фона

### Основные функциональные части:
- [ ]  Создание массива вершин дерева для текущего знания:
         1. Вершины пути вверх от основного знания до категории самого верхнего, 1-го уровня.
         2.  Вершины пути от текущего знания до основного знания включительно.
         3. Вершины - сестры текущего знания.
         4. Вершины - потомки текущего знания.
- [ ]  Создание ссылки на страницу "Легенда".:
- [ ]  Создание легенды- расшифровки цветов фона иконок категорий, знаний, видов знаний и связей.
- [ ]   Сортировка вершин - основных знаний по убыванию поля "Порядок" сущности "Знание"
- [ ]   Трехуровневая сортировка списка дочерних вершин-дополнительных знаний:
   1. сортировка связей по полю **Вид связи** в сущности **Связь**.  Группы связей выдаются в порядке убывания значения поля "Порядок" сущности "Виды связей".
   2.  сортировка связей по полю **Связанное знание**, где знания группируются по полю  **Вид -знания** в  сущности **Знание**.  Группы связей выдаются в порядке убывания значения поля "Порядок" сущности "Вид знания". 
   3.  сортировка знаний по полю "Порядок" сущности "Связь".
        Пример:  мне нужно, что вершины с видом связи "Аргументы" были сначала, затем "Контраргументы", затем вершины со всеми прочими видами связи. 
        Но, среди вершин-аргументов на 1-м месте были вершины с видом знания "Тезис", затем "Факт", затем "Цитата", затем вершины со всеми прочими видами знаний.
         В каждой группе вершин -видов связи-знаний, например, "Аргумент - Тезис", знания нужно отсортировать по убыванию поля "Порядок" сущности "Знание".
   4.  Название Темы знания есть ссылка:
          - для основных знаний - на страницу "Знание"
          - для дополнительных знаний - на объединенную страницу "Связь + Знание"
 ### Необходимые операции
- [ ] В модели **Вид знаний**. создать реквизит "Иконка"
- [ ] В модели **Вид знания** создать реквизит "**Порядок**".
- [ ] В модели **Вид связи** создать реквизит "**Порядок**".
- [ ]  В модели **Связи** создать реквизит "**Порядок**".
- [ ]  Админка. Страница **Вид знания**. Добавить поле "Порядок" .
- [ ]  Админка. Страница **Вид связи**. Добавить поле "Порядок" .
- [ ]  Админка. Страница **Вид знания**. Добавить поле "Иконка" .
- [ ]  Админка. Страница **Вид связи**. Добавить поле "Иконка" .
- [ ]  Админка. Страница **Виды знаний**. Добавить графу "Порядок" .
- [ ]  Админка. Страница **Виды связей**. Добавить графу "Порядок"
- [ ]  В сущность "Связь" добавить два реквизита "Источник" и "Комментарий к источнику"по аналогии с сущностью "Знание".

**Comment by lvb555** [comment]
**Дополнение к постановке задачи**

При поиске сестер и дочерей знания нужно отсеивать связи системных видов связи, типа "Ярлык", "Голосование".

**Comment by lvb555** [comment]
Тестовый материал подготовлен. На рисунке представлено, как оно должно быть на экране (категории, знания их порядок следования связей  и знаний)
![Результат тестирования - 100](https://user-images.githubusercontent.com/83456540/138655430-be792161-3fec-4d71-872c-dda466d83243.png)

**Comment by lvb555** [comment]
В этом древовидном представлении нужно сделать название вершины-названия видов связи в единственном или множественном числе в зависимости от числа у них дочерних вершин.

Для этого название вида связи должно содержать окончание в обоих числах в круглых и квадратных скобках, например, "Аргумент[ы]", "Цитат(а)[ы]"

Вопрос, как лучше:  Аргумент[ы]  или Аргумент()[ы]  ?

**Comment by breduin** [comment]
Аргумент[ы]
Цитат[а, ы]

**Comment by lvb555** [comment]
Продолжение разговора по последним двум комментариям. Мы обсуждали кодировку окончания слова для ед. и мн. чисел. Приводили примеры, состоящие из одного слова. А, если у меня есть такая запись в справочнике: "Элемент -последовательности"?

Нужно кодировать 1-е слово:  "Элемент [ы] -последовательности", т.е. выражение в квадратных скобках ищется по всей строке.
Вы не против?

**Comment by lvb555** [comment]
По поводу иконки для Вида знания.  Мы договорились помещать её в конце названия (Темы) знания.  Есть у меня сомнения, что эти иконки будут понятны пользователям, их ведь уже за двадцать, в памяти все не удержишь.  Я предлагаю так же в конце, но размещать само название Вида знания, разделяя его от Темы знания, скажем, " * ".
А после Вида знания через такой же разделитель поставить подстроку поля "Автор" до символа "-".
Пример:  "Аграрная реформа в целом оценивается положительно * Тезис * Шубин А.В."

Название Автора:  "Шубин А.В. - историк"

Таким образом мы переносим в новое представление контент старой таблицы раздела "Связанные знания".

**Comment by breduin** [comment]
каркасно сделал

**Comment by lvb555** [comment]
1. Дерево расцветает прямо на глазах!
2. Новый формат знания (Вид знания - Тема - Автор)  сейчас сделаны только для детей, а для всех прочих будет позднее?
2. Для понимания того, хорошо ли Вид знания ставить первым, нужно будет этот формат смотреть на всех вершинах (предки, -текущее -знания, сестры, дети).
3. Ну, и. конечно важна 3-мерная сортировка.

**Comment by lvb555** [comment]
Важная цветовая дифференциация знаний:  выделять голубым цветом шрифта знания, имеющие связанные знания (детей), а сиреневым цветом - знания, детей не имеющие.  Для чего это нужно?  Если я смотрю только саму логику, т.е. кроме Темы, Вида_знания и Автора мне более ничего не нужно, то по ссылке я пойду только в "голубое" знание, а открытие "сиреневого" знания мне не нужно.

**Comment by lvb555** [comment]
### Дополнение
Если Текущее знание - основное знание, то список всех -знаний текущей категории (Текущее знание и его сестры) должны быть отсортированы по убыванию поля "Порядок".

**Comment by lvb555** [comment]
-Этот комментарий не есть уточнение постановки задачи. Это всего лишь размышление, непосредственно связанное с этой задачей с тайной надеждой, а вдруг это возможно будет сделать уже сейчас.
Суть.  Мы много раз говорили, что конечно в идеале это ориентированный граф знаний, где знание может быть связано с -**несколькими** базовыми знаниями.  Но, как тогда показать путь к Текущему знанию (эта задача #100).  И было принято решение о том, что допускается только одно базовое знание (не граф, а дерево).  При этом -в -случае, если на какое-то знание нужно сослаться более одного раза, тогда создается ярлык этого знания и ссылка идет на этот ярлык  ([https://github.com/breduin/derzn/issues/66](url).
Но, хорошо, если знание, для которого создан ярлык не имеет детей.  А если под ним целое поддерево потомков?  Тогда нужно создавать целое поддерево ярлыков этих потомков с такими же связями, как у их оригиналов.  Если эта мера вынужденная (для пилотного проекта), то не слишком ли дорого обойдется программирование этих ярлыков.
А что, если допустить -возможным граф знаний, но при этом выдавать путь следования к Текущему знанию  с помощью создания -массива элементов- этого пути от предков до отца -включительно?  Может быть фактически Вы это уже и делаете? 
Мне это видится так:
1.  Открывая ссылку основного знания, мы создаем 1-й элемент массива
2. При -открытии ссылки дополнительного знания  (уже в древовидном представлении)  нужно понять, как открываемое знание относится к текущему знанию.  Возможны варианты:
   3.1.  Если открывается знание-предок, тогда в массиве "обнуляются" все элементы, соответствующие этому знанию и ниже.
   3.2.  Если открывается знание-сестра, тогда массив остается без изменений.
   3.3.  Если открывается знание-дочь, тогда в массив добавляется предыдущее текущее знание 
Таким образом, совсем неважно, что перед нами: граф или дерево знаний, мы просто запоминаем пройденный путь от основного знания до Текущего знания.
Очень важно Ваше мнение.  Скорее всего оно будет негативным, тогда я сделаю задачу на далекую перспективу.

**Comment by lvb555** [comment]
Функционал реализован в другой задаче
