### ISSUE TITLE
!!! Т - Админка. Категория. Поле "Содержание"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#103]
- [ ] Сделать поле "Содержание" форматируемым - подключить  CKEditor.
- [x]  Увеличить размер данных до 1024 (сейчас: 512).

**Comment by breduin** [comment]
сделал

**Comment by lvb555** [comment]
1.  При просмотре категории выдается HTML-текст, а не отформатированный текст. http://derzn.ru/drevo/category/75
2.  Длина поля увеличена даже более, чем до 2048. Интересно, каков максимум?

**Comment by lvb555** [comment]
Задача удалена по причине изменения концептуального взгляда нр категории.
