### ISSUE TITLE
!!! Проблема!  Окно просмотра знания

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#124]
При просмотре конкретного знания http://derzn.ru/drevo/znanie/591  в древовидной форме не выдаются его предки и категории, хотя связь этого знания с другим, базовым знанием есть: http://derzn.ru/drevo/znanie/515

Не связано ли это с тем, что у данной записи есть ярлык, Тема у -которого отличается на три символа "#2#" в самом конце: http://derzn.ru/admin/drevo/znanie/592/change/?_changelist_filters=q%3D%2522%25D0%2591%25D0%25BE%25D0%25BB%25D0%25B5%25D0%25B5%2B%25D1%2582%25D0%25BE%25D0%25B3%25D0%25BE%252C%2B%25D0%25BE%25D0%25BD%2B%25D0%25B1%25D1%2583%25D0%25B4%25D0%25B5%25D1%2582%2B%25D0%25B7%25D0%25B0%25D0%25B1%25D0%25BE%25D0%25BB%25D0%25B5%25D0%25B2%25D0%25B0%25D1%2582%25D1%258C%2B%25D0%25B2%2B%25D0%25B4%25D0%25B2%25D0%25B0%2B%25D1%2580%25D0%25B0%25D0%25B7%25D0%25B0%2B%25D1%2587%25D0%25B0%25D1%2589%25D0%25B5%252C%2B

**Comment by breduin** [comment]
очевидно, связано с тем, что для знания 591 у вас образовалось две связи - одна к базовому знанию, другая - к ярлыку. Мы как-то обсуждали единственность цепочки от знания к основному знанию. Вот здесь цепочка не единственная. Алгоритм берет первую попавшуюся цепочку и идёт по ней. Первой попадается цепочка с ярлыком, у которой, видимо, предков нет. Решение  - отфильтровывать виды связей при поиске цепочки предков, т.е. ярлыки не учитывать.

**Comment by breduin** [comment]
проверил, это связано с тем, что соотв. связь(565) не опубликована
