### ISSUE TITLE
!!! Ф - Просмотр знания.  Древовидное -представление текущего знания

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#125]
- [x] В процессе поиска -детей -текущего -знания -учитывать опубликованность соответствующих связей.  Неопубликованная связь трактуется как отсутствие связи.
- [x] В процессе поиска сестер -текущего -знания -учитывать опубликованность соответствующих связей.

**Comment by breduin** [comment]
сделал

**Comment by lvb555** [comment]
Проблема по 2-й подзадаче (сёстры).  Сделал неопубликованной -связь: <html>
<body>


496 | Вакцинироваться не нужно, бессмысленно и даже вредно! | Аргумент [ы] | Вакцины вредны самому вакцинированному человеку.
-- | -- | -- | --



</body>
</html>
Но связанное знание (сестра) все равно показывается: http://derzn.ru/drevo/znanie/524

**Comment by breduin** [comment]
поправил, проверьте

**Comment by lvb555** [comment]
Все хорошо. Спасибо.
