### ISSUE TITLE
!!! Т - Админка. Страница "Связи". Фильтрация по полям

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#126]
По аналогии со страницей "Знания" справа на странице -разместить наборы фильтров по полям:

1. Вид связи
2. Автор
3. Время и дата редактирования
4. Опубликовано

**Comment by breduin** [comment]
Время и дата редактирования - такого поля в модели Relation нет, есть только дата создания.
Остальное сделал.

**Comment by lvb555** [comment]
Все работает. Спасибо, очень нужно.
