### ISSUE TITLE
В модель "Категория" добавить текстовое поле "Содержание"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#13]
Это НЕОБЯЗАТЕЛЬНОЕ поле аналогично полю в Знании.  Оно нужно, чтобы описать суть этой категории. Установить длину поля "Содержание" до 2048.

При просмотре дерева вставить форму поля над деревом (сверху).

**Comment by breduin** [comment]
> При просмотре дерева вставить форму поля над деревом (сверху).

что значит "форма поля"? Для какой цели ее туда вставлять?

**Comment by lvb555** [comment]
Я хотел сказать, что при просмотре списка знаний категории значение поля поместить сразу под заголовком, но над списком знаний.  Впредь, буду стараться писать точнее..

**Comment by breduin** [comment]
сделал
