### ISSUE TITLE
В Знание добавить список меток

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#14]
Добавить в модель Знание, форму **Ввод знания** и в форму **Просмотр -знания** ( в самый низ.).

Вероятно, есть реализация механизма меток - по метке ссылке открывается страница со списком знаний, эту метку содержащих?

**Comment by breduin** [comment]
> Вероятно, есть реализация механизма меток - по метке ссылке открывается страница со списком знаний, эту метку содержащих?

ну да, это так же, как и Категории.

Метки представляют собой отдельные сущности. Их привязывают к сущности Знание. Одному Знанию может соответствовать много меток, т.е. при создании Знания нужен множественный выбор, верно?

**Comment by lvb555** [comment]
Да, множественный выбор.

А, что если  страница результата поиска по метке будет аналогично связанным знаниям, в форме двухуровневого списка, только на 1-ом уровне - категория?

**Comment by breduin** [comment]
сделал

**Comment by lvb555** [comment]
Спасибо, Олег Сергеевич!
