### ISSUE TITLE
Создание шаблона главной страницы

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#154]
-Будучи -адаптивным, шаблон в первую очередь должен быть ориентирован на мобильные устройства.

**Comment by Doriniel** [comment]
@lvb555 @breduin  Hola! **В ветке MariaP** сделала шаблон верстки главной страницы (не самого древа, а приветственный блок). Пока что шаблон адаптирован только для десктопа, когда согласуем финально дизайн - сделаю адаптацию для мобильных устройств.  Само дерево может идти под основным блоком. 

**Что еще не сделано**: планирую добавить в хэдер(шапку- меню) логотип проекта, + заменить выделение ссылки синим цветом при наведении на другой цвет/эффект. 
Футер будет "прибит" снизу, + узор из деревьев (см.последний скрин) или уберу, или заменю на другой цвет. Также в футере возможно разместить раздел "Контакты", либо просто параграф "Контакты" и e-mail в доменной зоне derzn.ru.
Превью прикрепляю:
![image_2022-02-16_00-38-27](https://user-images.githubusercontent.com/91247583/154154997-fd40aafd-3b43-41be-b8e2-a8148017c133.png)
![image_2022-02-16_00-39-13](https://user-images.githubusercontent.com/91247583/154155005-173f6e89-4cd4-4c6b-9d40-15c56e30bb9f.png)
![image](https://user-images.githubusercontent.com/91247583/154155349-9974b83d-32e4-4426-bb9d-9827f74fae82.png)

**Comment by lvb555** [comment]
Завершена
