### ISSUE TITLE
Ф - Страница "Авторы". Добавить поиск авторов по шаблону

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#157]
- [ ] На странице "Авторы" добавить пиктограмму "Лупа" для открытия страницы поиска авторов..  
- [ ] Структура страницы "Поиск авторов" во многом подобна странице "Поиск знаний"  (в расширенном режиме). Страница содержит два условия поиска:
-   Поиск по шаблону в полях "Имя"  и "Сведения об авторе"
-   Поиск по заданному Виду авторов 
- [ ]  Результаты представлены подобно знаниям:
- Количество найденных авторов, возможно, и нулевое значение.
- [ ]  Информация по автору выдается в два столбца:
1.  **Имя**, а под ним **Сведения об авторе**
2. **Вид автора** и **Число дней после изменения записи**

На **обсуждение**: что, если в случае единственного результата сразу же состоится переход на страницу этого автора?

**Comment by DemidovEvg** [comment]
Сделал такой вариант
![image](https://user-images.githubusercontent.com/88984484/163821435-0160f2a6-2f03-4d02-906c-f3eb998a68c7.png)

**Comment by lvb555** [comment]
1111
