### ISSUE TITLE
Добавить в модель "Связь" реквизит "Пользователь"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#18]
В модель **Связь** добавить системный реквизит «**Пользователь**» - указатель на таблицу « **Пользователи**». Заполняется автоматически.

**Comment by breduin** [comment]
сделано

**Comment by lvb555** [comment]
Хорошо бы в Админке внести реквизиты "Пользователь" и "Дата создания" по аналогии со списком Знаний
