### ISSUE TITLE
ДП - Дерево знаний - Поиск - Поиск в рамках категории

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#180]
Сейчас в режиме расширенного поиска есть возможность указать категорию (условие: "Категория").  Но при этом происходит фильтрация _основных_ знаний, привязанных _непосредственно_ к этой категории.  Но, справочник "Категории" многоуровневый, поэтому, если будет указана какая-то не конечная категория, а категория более высокого уровня, то ничего не найдется.

Необходим **полный, глубокий** поиск в рамках указанной категории:
1. Поиск проводится в рамках категории любого уровня.
2. Производится поиск не только _основных_, но и _дополнительных_ знаний, т.е. всех знаний, присутствующих в таких цепочках знаний, где 1-е знание цепочки содержится в рамках категории (согласно пункту 1.).

**Comment by DemidovEvg** [comment]
Предлагаю реализовать такой механизм:
1. Ищем все знания по категории. Находим все знания у которых указана категория
2. У каждого найденного знания находим все дополнительные
3. У каждого дополнительного находим его дополнительные, и так идем по иерархии до конца.
Таким образом реализуется обход всех деревьев найденных знаний на шаге 1.

Для реализации этого механизма предлагается создать дополнительный столбец в таблице знаний, в котором будет указан id знания к которому данное знание является дополнительным.

**Comment by lvb555** [comment]
Пункт 1 в Женином комментарии включает поиск основных знаний не только в указанной категории, но и всех её категорий.
