### ISSUE TITLE
!!! Админка. Увеличение ширины поля ввода

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#19]
Увеличить ширину поля ввода:
**Таблица Авторы:**

- [x] - Поле "Имя" -  раза в 2

**Таблица Знание:**

- [x] - Поле "Тема" - максимально, т.е. во всю строку (высоту поля в три строки)
- [x] - Поле "Категория" - раза в 3
- [x] - Поле "Вид знания" - раза в 3
- [x] - Поле "Источник" - максимально
- [x] - Поле "Комментарий к источнику" - максимально
- [x] - Поле "Автор" - раз в 6 

**Таблица Категории:**

- [x] - Поле "Название" -  раза в 2
- [x] - Поле "Parent" -  раза в 2

**Таблица Связи:**

- [x] - Поле "Вид связи" -  раза в 2
- [x] - Поле "Автор" - раз в 6

**Comment by breduin** [comment]
сделал, проверяйте

**Comment by lvb555** [comment]
Все сделано отлично, но возникли некоторые шероховатости:

- [x] 1. Знание. Название поля "Name" заменить на "Тема"
- [x] 2. Знание. Название поля "Content" заменить на "Содержание"
- [x] 3. Знание. Поле "Содержание" сделать необязательным
- [ ] 4. Знание. Поле "Содержание" Увеличить с 256 до 2048 

![Screenshot_1](https://user-images.githubusercontent.com/83456540/119604441-ba979480-bdf7-11eb-9747-a69bf2e7046f.png)

**Comment by breduin** [comment]
пп. 1,2 сделал. 
По остальным пунктам вы что-то путаете. Содержание и так было необязательным, это задание уже было. И размер его сейчас 2048.  На картинке - поле Тема, а не Содержание.

**Comment by lvb555** [comment]
Что-то меня переклинило,  извините.

**Comment by lvb555** [comment]
По пункту 3.  Поле "Содержание" сейчас опять обязательное!
![image](https://user-images.githubusercontent.com/83456540/119775328-1f242380-becc-11eb-8dbd-8ee0ac08504d.png)

**Comment by breduin** [comment]
добавил. Это уже свойства формы.

**Comment by lvb555** [comment]
Спасибо, все хорошо.
