### ISSUE TITLE
Представление реквизита Автор, как ссылку на знание о нем

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#20]
Для такого представления Автора при просмотре Знания нужно, как минимум:

1. в модель Автор добавить _**_необязательный_**_ реквизит **Знание** - указатель на таблицу **Знание**
2. Админка. В форму ввода  **Автор** добавить поле **Знание**.

Реквизит **Автор** присутствует как:
 - автор этого (базового) знания
 - авторы связанных знаний

**Comment by breduin** [comment]
>     в модель Автор добавить необязательный реквизит Знание - указатель на таблицу Знание

не очень понятно, зачем это нужно. Знание содержит обязательную ссылку на Автора. Т.е. автор данного Знания может быть найден (и указан) при помощи обратной ссылки. 
На какое Знание нужно ссылаться Автору?

**Comment by lvb555** [comment]
В дереве знаний будут  не только рассуждения (тезисы), факты, цитаты, вопросы и ответы, проблемы и решенияБ но и знания о людях, достойных этого - ГЕРОЯХ и АНТИГЕРОЯХ, и писаться они будут многими людьми, знавшими их лично или по книгам. Скажем автором знания-цитаты может быть Аристотель или Сталин.  Наверное, сумбурно, но здесь завязка их высказываний и данные об их жизни. Ссылка предполагалась на центральное знание об авторе **Вида** знаний**: **Биография**

Другое дело, что я погорячился - приоритет этой задачи очень невысокий и она может быть перенесена на очень далекую перспективу (версия 100.0)

 Кстати у задач можно выставлять приоритеты? Думаю, что нельзя.
