### ISSUE TITLE
Ф - Подписка на уведомления о новых знаниях (по авторам)

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#215]
### Описание сервиса
Сервис "Подписка на новые знания" предлагает три варианта подписки:
1. подписка по категориям
2. подписка по авторам
3. подписка по тегам

Эта задача - реализация подписки только по авторам.  Пользователь указывает список авторов.  При появлении  знаний этих авторов Пользователю направляется -уведомление на E-mail.  

### Необходимые операции:
- [x] На странице "Профиль" внизу под кнопкой "Сохранить" поместить кнопку  
"Подписка" для перехода на страницу  "Подписка", на которой Пользователь указывает/редактирует список авторов.  Позднее на эту страницу будут добавлены списки категорий и тегов.
- [ ] Структура страницы "Подписки": 
-  Заголовок  "Подписка по авторам"
-  Поле ввода "Авторы" (один ко многим).
Здесь будет полезен опыт создания подобного поля (условия) "Тег" в сервисе "Поиск"
![image](https://user-images.githubusercontent.com/83456540/168414952-24426177-993a-4dc5-8c9a-d27af1a53289.png)

- [x] Админка. Страница "Знание". При сохранении знания нужен контроль, не входит ли автор этого знаний в список авторов подписки.  Если входит, тогда отправляется сообщение.  Форма уведомления:
"
   Уважаемый, <Имя>
<Дата создания> было создано  новое знания:
<_Тема знания_>  
Автор: <Автор>
"
**Тема знания - ссылка на страницу этого знания**
- [x] Таблица "Пользователи".  Добавить реквизит "Подписки-Авторы" - указатели на Авторы (один ко многим)

**Comment by lvb555** [comment]
**Уточнение**
- [x]  Контроль подписки проводится ТОЛЬКО при сохранении опубликованного несистемного знания.
- Опубликованное знание - знание, у которого поле "Опубликовано" = **True**.
- Несистемное знание - знание, у которого Вид знания является несистемным (у него в записи поле "Системный"  = **False**).

**Comment by close2code-palm** [comment]
close2code-palm:issue215

**Comment by close2code-palm** [comment]
close2code-palm:issue215
