### ISSUE TITLE
!!! Создание раскрывающегося дерева

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#24]
1. Древовидное представление данных включает в себя категории и знания, присоединенные к категориям (нижний уровень дерева.
2. Использование пиктограмм 3-х видов: 
  - Категория раскрыта  - https://icons.getbootstrap.com/icons/file-plus-fill/
  - Категория свернута - https://icons.getbootstrap.com/icons/file-minus-fill/
  - Знание - https://icons.getbootstrap.com/icons/file-text-fill/
3. Цвет фона пиктограмм:
  - Категория -  желто-коричневый
  - Знание - голубой

**Comment by breduin** [comment]
> Категория раскрыта - https://icons.getbootstrap.com/icons/file-plus-fill/
Категория свернута - https://icons.getbootstrap.com/icons/file-minus-fill/

обычно такие значки используются наоборот, т.к. обозначают действия, а не состояния. Плюс значит раскрыть, минус значит свернуть.

**Comment by breduin** [comment]
цвета в ТЗ лучше задавать номерами, см. например https://www.artlebedev.ru/colors/

**Comment by lvb555** [comment]
Вы правы, я ошибся в написании, а именно это и подразумевал.

**Comment by lvb555** [comment]
Цвет фона пиктограмм:
Категория - FFCC66
Знание - 99CCFF

**Comment by breduin** [comment]
посмотрите

**Comment by lvb555** [comment]
1. Проблема:
 Категория "История" ушла вверх, а должна быть под категорией "Наука"
 Категория "Военнослужащие" должна быть под категорией "Кто он? Суд человеческий", а она ушла под "Искусство"
2. Желтый фон пиктограммы сейчас только на 1-м уровне, а должно быть на всех уровнях, кроме последнего.
3.  Цвет шрифта у неконечных категорий сделать черным - сейчас плохо видно, раскрыта она или нет.
4. Вопрос:  Вообще-то хотелось (и в формулировке было сказано), чтобы конечными вершинами дерева были основные знания,  поскольку это дерево знаний, а не дерево категорий.  Но, поскольку это, видимо, требует значительных затрат, то ладно, для 1-й версии сойдет и так.

**Comment by lvb555** [comment]
Поскольку основные знания будут непосредственно в дереве (т.е. раскрываться по крестику у категории), тогда можно окно просмотра категории не делать. Но в таком случае  поле "Содержание" нужно выдавать, как всплывающий комментарий при наведении курсора на категорию.  Впрочем, возможно, это аспект фронтенда, тогда извините.

**Comment by breduin** [comment]
сделал, посмотрите

**Comment by lvb555** [comment]
Всё замечательно!  Одно маленькие пожелания:  
1. Хорошо бы сделать на пиктограммах "Раскрыта категория" и "Свернута категория" знаки "+" и "-" выдавать темным, черным цветом.
2. Хорошо бы убрать подчеркивание в названиях категорий и знаний.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Вот теперь просто чудесно!  Спасибо Вам, Олег.
