### ISSUE TITLE
Ф - Админка. Анализ предложений экспертов

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#245]
Особенностью интервью экспертов (опросов) является то, что они не только выбирают ответы из заданного списка ответов, но и вносят предложения по новым ответам.  Это дает возможность расширять список ответов.  Любое предложение анализируется Администратором, в результате которого им принимается решение о создании новых ответов, т.е. о создании новых знаний и новых связей вида "Ответ".
Эта задача - Создание инструмента анализа администратора.действия которого таковы:
1.  В админке он по ссылке "Анализ предложений"  переходит на страницу "Предложения экспертов"

**Comment by Intey** [comment]
Возможно стоит задуматься над объединением предложений экспертов по контексту "Вопрос", а не по Интервью.
Предпоссылка к такому предложению:

Администратор в процессе анализа ответов экспертов, имеет возможность (и должен, наверно) находить дубликаты и исправлять такие случаи. Чтобы визуально это было проще, мы можем собирать страницу "Анализ предложений экспертов" таким образом, что мы объединяем ответы по вопросам. Шанс повтора ответа/предложения на 1 и тот же вопрос больше, чем на разные (простая логика).

**Comment by lvb555** [comment]
сделано в другой задаче
