### ISSUE TITLE
Ф - Создание страниц "Мои интервью"" и "Интервью эксперта" 

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#247]
### Эксперты, кто они?
Существуют два класса пользователей сайта:  те, кто готовит контент, и те, кто его смотрит.  Эксперты на нашем портале – пользователи, которые приносят свои знания, тем самым обогащая контент. Эксперты – специалисты в каких-то конкретных областях знаний.  Дерево знаний содержит знания из разных областей, поэтому эксперт может создавать  знания в пределах своей компетенции. Компетенции описываются набором категорий дерева знаний, в рамках которых эксперт может проявлять свою активность:  создавать новые знания и участвовать в интервью.    
### Интервью, что это такое?
Интервью форма опроса мнений одного или нескольких экспертов по набору вопросов в рамках определенной теме.  Опросы общественного мнения (ООМ) от интервью отличаются по двум аспектам:
•	В ООМ участвует любой человек, в интервью – эксперт.
•	В социологии в ООМ используются вопросы закрытые (т.е. с набором ответов) или полуоткрытые (где есть еще ответ «Другое»).  В журналистике в интервью используются исключительно открытые вопросы, ответами на которые являются некоторые высказывания участников.  Итак в социологии выбирают, в журналистике говорят (пишут).

Наша технология соединяет методы социологии и журналистики.  Эксперты выбирают ответ (ы) из списка уже заданных вариантов и (или) добавляют новые ответы (это предложения экспертов), если видят в этом необходимость.  Администраторы могут принимать отдельные предложения, тогда они пополняют набор вариантов ответов.
### Оформление интервью в Дереве знаний
 
![image](https://user-images.githubusercontent.com/83456540/173755918-01635aa7-bab6-4d68-9728-5d16c04ac087.png)

В Дереве Знаний для каждого интервью создается своя система метазнаний.
Метазнание вида «Интервью» связано с несколькими метазнаниями вида «Вопрос интервью» (вид связи «Состав»).  Для интервью указываются дата начала и дата окончания интервью с помощью связанного метазнания вида «Период интервью» (вид связи «Период интервью».
Метазнание вида «Вопрос интервью» связано со знанием – вопросом связью вида «Объект интервью». Для каждого вопроса интервью указываются Число допустимых ответов при голосовании с помощью связанного метазнания вида «Число» (вид связи «Число ответов»).
Набор знаний – вопросов, связанных со своими знаниями - ответами образуют информационную основу интервью. 
Раздел портала «Мои интервью»
Данный раздел дает возможность экспертам участвовать в проведении интервью – отвечать на вопросы путем голосования.  Это инструмент эксперта.  Слово «Мои» относится к эксперту, к его восприятию информации.  Это его интервью, на какие-то из них он, видимо, уже ответил, другие ждут его участия.
### Архитектура раздела «Мои интервью»
 
![image](https://user-images.githubusercontent.com/83456540/173756125-1df13ea1-4b1e-4270-96e3-83e87300fecd.png)

### Навигация по разделу
1.	Пользователь может открыть страницу "Мои интервью" с помощью пункта «Мои интервью» в подменю «Другое» главного меню сайта. 
 
![image](https://user-images.githubusercontent.com/83456540/173756372-937984a8-9808-44e0-829b-f2f350f1bea6.png)

Внимание!  Этот пункт возникает только в случае пользователя – эксперта, т.е. у такого пользователя, у которого есть список категорий в таблице «Категории – Эксперты».
Структура страницы "Мои интервью ": одноименный заголовок и список интервью эксперта.  Этот список получается по алгоритму:
1.	Фильтрация списка категорий из таблицы «Категории – Эксперты» по условию: поле «Эксперт» = Текущий Пользователь.
2.	Поиск во всех категориях из списка всех метазнаний вида «Интервью».

Список представлен в древовидной форме "Категория-Знание".
Рядом с названием (Темой) знания нужно указывать в скобках: <Число вопросов, отработанных экспертом> / <Общее число вопросов интервью>.

Элементы списка - ссылки на соответствующие им страницы "Интервью эксперта».
Знания-интервью сортируются по убыванию даты создания (от новых к старым).
Цвет шрифта интервью в списке бывает зеленый и красный:
1.	Красным цветом выделяются те интервью, в которых эксперт может принять участие.  Для этого должны выполняться условия:  Текущая дата находится в рамках периода интервью
2.	Зеленый цвет используется в других случаях. Здесь по ссылке происходит переход на страницу "Результаты голосования экспертов"

Выбрав интервью, т.е. перейдя по ссылке эксперт попадает на страницу «Интервью».

![image](https://user-images.githubusercontent.com/83456540/173756602-c0976593-aa35-4617-9204-ebc6944506b4.png)
	 
Структура страницы "Интервью эксперта":
•	«Тема интервью:» + поле «Тема» этого интервью.  Это ссылка на само текущее интервью.
•	Заголовок «Вопросы интервью»
•	Список ссылок на вопросы интервью – список знаний,связанных с метазнанием вида «Интервью» по виду связи «Состав»
Порядок действий:
1.	Получение списка вопросов
2.	Сортировка списка вопросов убыванию поля «Порядок». 

### Необходимые операции в самом начале работы над задачей

- [ ] Создать новую модель "Категории - Эксперты" со структурой:

1.	поле "Эксперт" - указатель на таблицу "Пользователи"
2.	поле "Категория" - указатель на таблицу "Категории"
- [ ] Админка. Разместить здесь таблицу "Категории - Эксперты"

**Comment by lvb555** [comment]
### Дополнения
- [x]  Изменение в концепции.  **Период интервью - необязательный параметр**.  Необходима корректировка кода окраски интервью в списке.
Параметр задается парой значений дат.  Я предлагаю варианты такие:
1. две даты
2. дата до дефиса.  "Есть у революции начало, нет у революции конца".  Тогда конечной датой считаем:  Текущая_дата +1
3. дата после дефиса.  Нет начала.  Тогда начальной датой считаем:  Текущая_дата -1
4. вообще нет параметра (т.е. такого знания на связи "Период...".    
Тогда начальной датой считаем:  Текущая_дата -1
Тогда конечной датой считаем:  Текущая_дата +1
И больше в запросах ничего менять не надо.  Так?
- [x] Страница "Мои интервью".  К теме интервью справа (после скобок) добавлять информацию о периоде его проведения  (значение поля, как есть без изменения или ПУСТО при отсутствии параметра).

**Comment by lvb555** [comment]
- [x] Ошибка.  "Мои интервью".  Если в метазнании "Период интервью" не указана конечная дата, тогда выдает: 
![image](https://user-images.githubusercontent.com/83456540/176093774-7b4aa0e0-b1a6-479f-b27b-2ad63c21b51b.png)
- [x] Ошибка.  "Мои интервью".  Если в метазнании "Период интервью" не указана начальная дата, тогда выдает: 
![image](https://user-images.githubusercontent.com/83456540/176094510-0f484560-f1c0-4719-bfaa-96adb741c6e1.png)
- [x]  Ошибка: "Мои интервью".  Если в метазнании "Период интервью" не указана ни начальная, ни конечная дата, тогда интервью выдается зеленым цветом, а должно быть красным.  
- [x]  Ошибка: "Мои интервью".  Если отсутствует метазнание "Период интервью" тогда интервью выдается зеленым цветом, а должно быть красным.  
- [x]   Замечание:  Страницу "Интервью" нужно сделать согласно постановке задачи.
![image](https://user-images.githubusercontent.com/83456540/176100448-a91cb1db-4f5b-4d27-b9a9-4c756d552df6.png)
- [x] Дополнение:  Страница "Мои интервью".  Добавить легенду:
![image](https://user-images.githubusercontent.com/83456540/176102751-3b3fdc29-25f5-4cf6-8d31-6436fb5afab2.png)
- [x] Дополнение:  Период интервью нужно выдавать тем же цветом, что и само название интервью и число вопросов в нём.
- [x] Дополнение.  Моя большая ошибка в постановке. Везде в задаче, где используются записи таблиц "Связи" и "Знания" мы берем только ОПУБЛИКОВАННЫЕ знания и связи. (т.е. поле "Опубликовано" = True.

**Comment by lvb555** [comment]
- [x] Ошибка:  Возникает при открытии страницы "Мои интервью", если в качестве компетенции выбрана категория, являющаяся родителем к категории, содержащей интервью.  Для примера зайдите от администратора - admin.
![image](https://user-images.githubusercontent.com/83456540/176388400-fb8fd3a1-d6c8-488d-9a6b-9da3f68a03eb.png)

- [x]  Проблема:  Админка. Эксперт.  Если я, находясь в окне выбора "Категория"  щелкну мышкой без нажатой клавиши Ctrl? , тогда ранее введенная информация (возможно, в другую сессию) пропадает. Предлагаю блокировать событие клика мыши без нажатия  Ctrl.

**Comment by DaniilMelnikov** [comment]
Период интервью указывается по шаблону 03.07.22-, или -03.07.22, или 03.07.22-05.07.22. Если указать год 2022, то регулярное выражение перестанет работать

**Comment by lvb555** [comment]
- [x] Задание 
![image](https://user-images.githubusercontent.com/83456540/177338785-d68b1187-b3b3-4420-b9f9-7b6a330ae33e.png)
выполнено не полностью.  Всякие вычисления дат при их отсутствии не нужно выносить на экран, там должно быть **"как есть"** в Теме этого знания.
- [x] При отсутствии конечной даты, её значение равно в зависимости от условия. 
Если Тек. дата <  Нач. дата тогда Кон.дата := Нач. дата + 1
Иначе  Кон.дата := Тек. дат +  1
- [ ] При отсутствии начальной даты, её значение равно: Нач.дата := Тек. дата - 1
- [x] Не дополнение, а мысль вслух.  Код немного жестковат для пользователя: "Шаг вправо, шаг влево - прерывание.  Это относится к формату описания периода интервью.  Если между дефисом и начальной или конечной датой стоит(ят)  пробел(ы), то выдается прерывание.  Скорее всего поиск дефиса не реализуется.
![image](https://user-images.githubusercontent.com/83456540/177341785-df2011c4-c550-4f98-9a4b-f64e1ad125d3.png)
- [ ]

**Comment by lvb555** [comment]
- [ ] При отсутствии начальной даты, её значение равно в зависимости от условия.
Если Тек. дата > Кон. дата тогда Нач.дата := Кон. дата - 1
Иначе Нач.дата := Тек. дат - 1

**Comment by lvb555** [comment]
Задача выполнена
