### ISSUE TITLE
!! Админка. Создание нового знания на основании -текущего знания

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#25]
Два варианта, но 1-й симпатичнее
1  В Список знаний подвесить кнопку "Ввод на основании", по которой происходит:
    - копирование текущей записи
    - открытие ее для редактирования. 
2. В Знании подвесить кнопку "Ввод на основании", по которой происходит:
    - копирование текущей записи
    - открытие ее для редактирования

**Comment by breduin** [comment]
использовал встроенные возможности админки. Практически 2-й вариант. 
Открываете Знание, которое нужно скопировать, меняете тему (она должна быть уникальной, иначе не запишется) и внизу новая кнопка: **Сохранить как новый объект** - нажимаете её, запись сохраняется как новый объект, можно дальше её редактировать, но для сохранения уже нажимать **Сохранить**.
Посмотрите.

**Comment by lvb555** [comment]
Прекрасно работает. Спасибо, Олег Сергеевич!
