### ISSUE TITLE
! Админка. Фильтрация выпадающего списка. "Знание" - "Метки

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#27]
Админка. Окно ввода / редактирования "Знание". Поле "Метки". Выпадающий список

Фильтрация элементов списка после ввода буквы.

**Comment by breduin** [comment]
сделал

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Отлично. Пришлось изменить формат списка результатов?
