### ISSUE TITLE
Т - Создание раздела "Технологический процесс подготовки знаний"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#276]
Постановка задачи изложена в присоединенном файле: 
[Универсальный алгоритм.pdf](https://github.com/breduin/derzn/files/9197568/default.pdf)

**Comment by lvb555** [comment]
### Дополнения
- [x] При установлении статусов "Опубликованное ПредЗнание" и "Опубликованное Знание"  в поле "Опубликовано" заносить значение True.
- [x] При установлении статусов "ПредЗнание в КЛЗ" и "Знание в КЛЗ"  в поле "Опубликовано" заносить значение False.
- [ ] При установлении статусов "Экспертиза-2 ПредЗнания" и "Экспертиза-2 Знания" отправлять сообщение с предложением оценить корректность этого знания и дополнить его другими знаниями".  _**Этот пункт написан для памяти постановщика..**_
### Для информации
**Организация переходов на страницы этапов**
![image](https://user-images.githubusercontent.com/83456540/184192129-aae2ed69-6882-4ecf-88de-654495a80f13.png)

**Comment by lvb555** [comment]
### Дополнения к постановке задачи:
- [x]  В сущность "Пользователи" добавить логический реквизит "Редактор", по умолчанию такой роли нет.
- [x]  В сущность "Пользователи" добавить логический реквизит "Руководитель", по умолчанию такой роли нет.
- [x]  В сущность "Пользователи" добавить логический реквизит "Член_КЛЗ", по умолчанию такой роли нет.

**Comment by lvb555** [comment]
**Проблема.** У нас для публики есть две страницы "Дерево знаний" для авторизованных и не авторизованных пользователей. Вопрос, как организовать к ним доступ и переключение с одной на другую после завершения авторизации пользователя.

**Comment by sergeybv26** [comment]
> **Проблема.** У нас для публики есть две страницы "Дерево знаний" для авторизованных и не авторизованных пользователей. Вопрос, как организовать к ним доступ и переключение с одной на другую после завершения авторизации пользователя.

Можно решить стандартным разграничением прав в Django. На сколько я понимаю неавторизированные пользователи не могут создавать знания, ну и соответственно редактировать.

**Comment by lvb555** [comment]
### Изменения
- [x]  При открытии записи со статусом "Готовое знание" происходит следующее:
1. Автоматически устанавливается статус "Экспертиза ПредЗнания".
2. В реквизит "Эксперт" заносится значение текущего пользователя.
- [x]  При наличии статуса "Экспертиза ПредЗнания" добавить кнопку-операцию "Отказаться от экспертизы ПредЗнания", по которой устанавливается статус "Готовое ПредЗнание".
- [x] Знания со статусом "Отклоненное ПредЗнание" сделать доступными для всех экспертов (в зонах их компетентности). 
Новая версия файла с описанием этапов: 
[Описание 6 этапов - вер.7 .xlsx](https://github.com/breduin/derzn/files/9403568/6.-.7.xlsx)

**Comment by lvb555** [comment]
### Дополнения
- [x] В сущность "Статус знания" добавить целочисленный реквизит "Лимит времени".
- [x]  Админка. таблица "Статусы знаний".  Добавить  реквизит "Лимит времени".
- [x]  Админка. таблица "Статусы знаний".  При создании записи  значение реквизита "Лимит времени" установить в 1000 (дней).

**Comment by sergeybv26** [comment]
[Описание 6 этапов - вер.8.xlsx](https://github.com/breduin/derzn/files/9423958/6.-.8.xlsx)

**Comment by lvb555** [comment]
### Изменение
Изменение структуры меню для функционала ТП "Подготовка знаний"
![image](https://user-images.githubusercontent.com/83456540/189471427-431bab59-e076-416b-b3d4-26f0a4bdab27.png)
Жирным шрифтом указаны пункты меню, связанные с этим ТП.

**Comment by lvb555** [comment]
### Дополнение.  Заглушки на страницах изменения знания и его статуса
   Любой пользователь может иметь несколько ролей в любом их сочетании.  Любой пользователь имеет роль "Публика". Возможны наборы ролей:  "Эксперт - Публика", "Редактор - Публика", "Эксперт - Редактор - Публика", "Руководитель - Публика", "Руководитель - Эксперт - Публика" и т.д.
   Поэтому необходимы специальные меры - "заглушки", препятствующие тому, чтобы 
 редакторы, руководители не смогли обработать  знания, созданные ими самими.

  ### Набор "заглушек"

- [x]  **Этап "Редактирование ..."**.  Редактор не должен редактировать и изменять статус Знания, им созданного.
**Если**  Создатель = Текущий_пользователь **Тогда** 
1) Выдать сообщение: "Невозможно редактировать свое собственное знание"
2)  Возврат на страницу этапа

- [x]  **Этап "Публикация ..."**. Руководитель не должен изменять само Знание и  статус Знания, им созданного.
**Если**  Создатель = Текущий_пользователь **Тогда** 
1) Выдать сообщение: "Невозможно публиковать свое собственное знание"
2)  Возврат на страницу этапа

**Comment by lvb555** [comment]
- [x]  Страница  "Создание/редакт. знания".  Поле выбора "Вид знания".  Выпадающий список нужно предварительно сортировать по алфавиту.
- [ ]  Страница  "Создание/редакт. знания".  Поле выбора "Метки".  Сейчас неловкое движение мыши и теряется значение.  Нужно сделать так, чтобы выбор/отмена выбора происходили по двойному клику.
- [x]  Изменение знания. Дерево. При клике мышью по самому знанию происходит прерывание.  При клике на карандаш - норм. 
- [x]  Проблема.  Изменение предзнания. Дерево.  Категории самого нижнего уровня не являются пиктограммами с желтым крестом и раскрываются путем входа в саму категорию. Нужно сделать основанием для желтого крестика не только наличие дочерних категорий, но и знаний.
- [x]  Проблема.  Изменение предзнания. Дерево. Категория выдается независимо от того, есть внутри неё знания или нет. Должны выдаваться только категории, имеющие знания или категории, имеющие такие категории.
- [x]  Страница "Создание/редакт. знания".  Добавить кнопки "Сохранить и продолжить" и "Закрыть".  Последняя нужна уже потому, что если я захочу прекратить ввод/редактирования", то я вынужден закрывать вкладку, выйти из Дерева.
- [ ]  Проблема. Страница  "Создание/редакт. знания".  При сохранении справедливо выдалась ошибка "
- [ ] Запись с такой Темой уже существует".  Но, когда я сделал тему заведомо уникальной сообщение всё равно выдавалось.  Решение: при выправлении ситуации сообщение это **нужно удалять.**
- [x]  Поле "Категория" нужно сделать обязательным.  Весь ТП рассчитан только на основные знания.
- [x]  Поле "Категория".  Выпадающий список должен содержать только опубликованные категории, а не все, как сейчас"
- [x]  Проблема.  Сейчас эксперт может создать знание в любой категории. Эксперту должно разрешаться создавать знания только в пределах своей компетентности.
- [x]  Проблема.  Эксперт создал Знание и на странице "Изменение Знания" видит кнопку "Завершить ПредЗнание".
- [x]  Страница "Создание/редакт. знания".  Кнопку "Сохранение Знания" переименовать в "Сохранение"
- [ ]  Страница "Создание/редакт. знания".  По кнопкам изменения статуса нужно  проводить сохранение записи.
- [ ]   Страница "Создание/редакт. знания".  Добавить кнопку "Удалить" при некоторых статусах.
- [ ]  Страница "Создание/изменение знания"  Добавить логический реквизит "Нет ссылки".  Это в соответствии с задачей:  https://github.com/lvb555/derzn/issues/412
