### ISSUE TITLE
!!! Админка. Знание. Метки. Сортировка списка меток

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#28]
Сортировка списка меток по алфавиту

**Comment by breduin** [comment]
метки сейчас так и отсортированы - по алфавиту. Просто сначала идут метки, отсортированные по заглавным буквам, затем - по строчным, см.

```
Косыгин
Столыпин
важно
гражданская_война_ 1918-1920
политика
реформа
сельское хозяйство
```

Нужна сортировка независимо от регистра первой буквы?
Такая:

```
важно
гражданская_война_ 1918-1920
Косыгин
политика
реформа
сельское хозяйство
Столыпин
```

?

**Comment by lvb555** [comment]
Нет, не нужно.
