### ISSUE TITLE
Ф - Страница просмотра знания. Добавить число просмотров знания.

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#30]
Внизу страницы "Знание", над разделом "Древовидное представление знания"
 -поместить  "Число просмотров" и само число просмотров этого знания.

**Comment by lvb555** [comment]
Тимур, переходим в Телеграм для связи. Сообщи, пожалуйста, свой ник.

**Comment by undm-link** [comment]
https://t.me/AverinTimur

**Comment by lvb555** [comment]
Задача сделана.  Спасибо Тимуру!
