### ISSUE TITLE
Т - Модификация сервиса "Поиск":  исключение из поиска знаний системных видов знаний

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#304]
В дереве знаний есть два типа знаний:  системные и несистемные.  Несистемные знания видны пользователям в опубликованном случае.  Системные знания играют служебную роль и используются для создания сложных знаний:  таблиц, интервью, тестов.

Системность знания определяется системностью его Вида знания.

Виды знаний в своем описании имеют реквизит "Системный".  Если он включен, то Вид знания, а, значит, и все знания этого вида являются системными и должны быть исключены из результатов поиска.

**Comment by DemidovEvg** [comment]
Исключение системных видов знаний из поиска реализовано!
