### ISSUE TITLE
Создание раздела "Помощь"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#319]
- [ ]  На страницах сайта, в header поместить пиктограмму "?"  для перехода на страницу "Помощь" в контексте текущей страницы. 
- [ ]  Создать таблицу "Помощь" с реквизитами:
-  "Заголовок" - строка
-  "Родитель" - указатель на запись этой же таблицы.
-   "Код страницы" -строка
-  "Содержание" - длинное строковое, типа мемо-поле.

Код страницы - часть URL-адреса  после drevo\  и до числа, если оно есть, или до конца адреса.  Коды страниц:
       Вид страницы       Код
1.  Дерево знания         пусто 
2. Знание                      znanie
3. Авторы                       authors
4. Автор                          author/
    **...**
- [x] . В Админке разместить таблицу "Помощь".
- [ ]   Админка. Помощь.  К полю "Содержание" присоединить CKEdit  для форматирования текста с настройками подобно полю "Содержание" на странице "Знание".
- [x] Создать страницу "Помощь"  со структурой:
1.  Заголовок - реквизит "Заголовок"
6.   Путь к текущей странице - последовательность ссылок на страницы "Помощь"  от верхней до текущей страницы,  Для разделения элементов и перед 1-м элементом вставить символ "●".
7.   Содержание - реквизит "Содержание"

**Comment by DemidovEvg** [comment]
Навигацию может такую?
![image](https://user-images.githubusercontent.com/88984484/194021215-91d82606-3e40-4b6d-bd2b-37cb8be49d52.png)
==========================
А какая структура раздела помощь? Тоже будет дерево?
![image](https://user-images.githubusercontent.com/88984484/194022015-b1e51e5c-bbf1-47db-88ef-16f1b43292e8.png)

И главное назначение раздела какое?

**Comment by Intey** [comment]
@DemidovEvg Ну как я понимаю - дать документацию =) А саму задачу я понимаю как 2 сценария:
1. Я как пользователь системы хочу разобраться в системе и понять как ей пользоваться. Для этого мне нужна документация.
2. Я как администратор платформы, хочу удобный инструмент для редактирования справочной информации/документации, чтобы поддерживать ее актуальность для пользователей.

**Comment by breduin** [comment]
`в контексте текущей страницы`

из алгоритма непонятно, как контекст учитывается.
Т.е., по идее, нужно открывать сразу страницу Помощи с информацией, которая привязана к той информации, со страницы которой Помощь вызывается.
Или просто открывается страница с оглавлением и юзер ходит по ссылкам, куда ему надо?

**Comment by DemidovEvg** [comment]
Например у гугла есть разделы: 
- Help где есть строка поиска, например как отправить письмо и тебе вылазит описание как это сделать
- Training который включает в себя обучение пользованию сервисом. Честно я ни разу в Training не заходил)

**Comment by lvb555** [comment]
### Спасибо за активную ПОМОЩЬ в создании ПОМОЩИ!)))
Предполагается две версии раздела.  

Ответы на вопросы:
1.  По пиктограмме переход сразу на страницу Помощи по этой странице сайта (не оглавление всего раздела "Помощь").  Выход на оглавление будет со странице помощи по кнопке.
2. В структуру таблицы "Помощь" добавлен реквизит "Код страницы" для идентификации нужной страницы помощи  по URl-адресу текущей страницы сайта..  
Коды страниц:
       Вид страницы       Код

-  Дерево знания         пусто 
-  Знание                      znanie
-  Авторы                       authors
-  Автор                          author/
    **...**

3.  Дима дерево "Помощь" будет во 2-й версии. 
4.   Женя,  твоя инфо может быть очень полезна тоже во 2-й очереди
