### ISSUE TITLE
!! Админка. Создание новой связи на основании -текущей связи

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#34]
Админка. В **Связи** подвесить кнопку "**Сохранить как новый объект**", по которой происходит:
- копирование текущей записи
- открытие ее для редактирования

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Я дважды попробовал, есть проблема:  в результате создается два объекта: новый и еще одна копия текущей связи.

**Comment by lvb555** [comment]
Работает корректно.  Немного отличаются наборы кнопок у Знания и Связи, но, я предположил, что это как-то связано с тем, что у Знания есть требование уникальности Темы, то у Связи такого требования нет, так как и быть не может.
