### ISSUE TITLE
! Админка - Связи. Сделать  поиск связей (как сделано в Знаниях)

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#35]

**Comment by breduin** [comment]
сделал поиск по базовому знанию, и по связанному, проверьте.

**Comment by lvb555** [comment]
Замечательно. Наверное, мне нужно более четко формулировать задачки, но тут такой психологический момент, что идет как бы переложение существующей системы, т.е. для меня это не с нуля и уже есть некая замыленность. Но, я  постараюсь...  В данном случае фильтрация по обоим полям для меня была АБСОЛЮТНО очевидна.
