### ISSUE TITLE
!!! Проблема:  Админка. Знания.  Резко уменьшилась ширина графы "Тема"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#36]
Нужно значительно увеличить ширину графы  "Тема" за счет:
1. снизить до 30 символов  ширину графы "Источник". Значение поля "Источник" здесь нужно только для информации о его наличии/отсутствии.
2. снизить до 30 символов  ширину графы "Автор".  Здесь важна только фамилия, а вид деятельности, должность не важны.

**Comment by breduin** [comment]
1. честно говоря, не вижу резкого уменьшения ширина графы Тема. Пришлите скрин, чтобы было понятно, о чем речь. 
2. вы давали задание https://github.com/breduin/derzn/issues/19:

> Увеличить ширину поля ввода:
> ...
> Таблица Знание:
> 
>  - Поле "Источник" - максимально
> - Поле "Автор" - раз в 6

сейчас вы даете прямо противоположное задание. Есть уверенность, что это не превратится в цикл?

**Comment by lvb555** [comment]
Олег Сергеевич, тут возникло небольшое взаимное недопонимание. В задаче #19  речь шла о полях ввода в окнах ввода/редактирования,  а здесь я говорю о ширинах граф списка записей Знания. Подскажите, пожалуйста, какую терминологию использовать для полного понимания

**Comment by lvb555** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/83456540/119703503-455faa00-be5f-11eb-9117-7c5068f467b5.png)

**Comment by breduin** [comment]
ясно. Речь про ширину столбцов в списке Знаний. 
Можно ссылку давать на страницу, по которой ставится задача.

**Comment by lvb555** [comment]
Хорошо, я учту.

**Comment by breduin** [comment]
сделал

**Comment by lvb555** [comment]
Фильтры справа смотрятся симпатично.  Что касается задачи,  то в принципе удовлетворен. Но реальная практика может потребовать некоторые коррективы.
