### ISSUE TITLE
!!! Админка. Знание. Свойство формы. Сделать поле "Автор" необязательным.

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#39]
Понятно, что для тезисов и цитат автор всегда должен быть.  Но для знания вида "Вопрос" автор не всегда нужен. 

Поскольку я уже отказался от 1с-сервиса и начал потихоньку наполнять контент (знаю, что рискую),  то именно этим определяется высокая приоритетность задачи (ну еще и то, что это делается при умении довольно несложно)..

**Comment by breduin** [comment]
сделал, проверьте.

А в чём риск? Давайте на ваш домен поставим это всё, база у вас под руками всегда будет.

**Comment by breduin** [comment]
собственно, можно сделать поле Автор обязательным или необязательным в зависимости от значения другого поля, в т.ч. и от вида знания.

**Comment by lvb555** [comment]
Работает.
1.  Я бы только приветствовал перенос на derzn.ru.  Необходимые данные для для входа на reg.ru я передавал.
2. По поводу обязательного авторства.  Конечно это хорошо управлять обязат/необязат в зависимости от Вида знания. Видимо для этого нужно в модель и форму Знание добавить логический реквизит (по умолчанию - необязательно).
3. Аналогичное управление хорошо бы ввести и для Связей.  Там тоже обязательность не всегда будет нужна.
