### ISSUE TITLE
Ф - Верстка шапки, футера и главной страницы сайта.

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#396]
- [ ] Верстка шапки сайта, согласно макета основного шаблона:  https://www.figma.com/file/aw2bMraplkaoFdi0E4Cqjt/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9?node-id=0%3A1&t=ljOhApyhKAefBz3S-1
- [ ] Верстка футера сайта, согласно макета основного шаблона
- [ ]  Разделить главную страницу (от начала до 2-й цитаты включительно) на, собственно, главную (от начала до 2-й цитаты включительно) и раздел "Дерево знаний" (само дерево знаний).
- [ ] Верстка главной страницы с использованием контента из файла: 
[ПРОБА --- ДЗ - Главная стр. - вер.4 - 29.11.22.docx](https://github.com/lvb555/derzn/files/10123004/---.-.-.4.-.29.11.22.docx)

**Comment by strnikolay** [comment]
Здравствуйте! Нашел задачу на https://freelance.habr.com/
Не совсем понял где взять макеты.
И как я понял backend на python.

**Comment by lvb555** [comment]
### Дополнения
- [ ]  В основное меню, справа от "Теги" поместить пункт "Подготовка знаний".   
- [ ]  В основное меню, справа от "Подготовка знаний" поместить пункт "Панель управления".   Этот пункт появляется только для администраторов.

**Comment by lvb555** [comment]
- [ ] Нижнее меню. Пункт "Панель управления" переместить в верхнее меню, крайним справа.
