### ISSUE TITLE
! Админка. Фильтрация выпадающего списка.  "Связь" -"Базовое знание"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#4]
Админка. Окно ввода/редактирования "Связь".  Поле "Базовое знание". Выпадающий список 

Фильтрация элементов списка

Вы сказали: "можно сделать, Можно еще вот такую ​​штуку поставить: https://django-ajax-selects.readthedocs.io/en/latest/".    

Я правильно понимаю, что после ввода новой буквы происходит новая фильтрация?

**Comment by breduin** [comment]
> Я правильно понимаю, что после ввода новой буквы происходит новая фильтрация?

да

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Можно при фильтрации не учитывать регистр?
