### ISSUE TITLE
Т - Админка. Создание знания.  Требование обязательности заполнения в контексте Вида знания.

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#42]
- Демократизм процесса -создания -знаний с участием множества пользователей требует хорошей детализации требований по заполнению полей в зависимости от контекста

Есть стандартный способ объявления того или иного поля обязательным для заполнения.  Но это безусловный способ - он не зависит от контекста.  Но, бывают ситуации, когда для одних знаний требование обязательного заполнения должны быть, а для других обязательность не требуется.

Ну, например, для знания вида "Цитата"  поле "Автор" является обязательным.

Страница ввода/редактирования знания.  Условно обязательными являются такие поля:

1. Поле "Автор", если логический реквизит таблицы "Вид -знания" "Наличие автора"=True
2. Поле "Источник", если логический реквизит вида знания "Наличие источника"=True 

**Необходимые операции**

1. Модель/форма **Вид знания**.  Добавить логический реквизит/поле "Наличие автора"
2. Модель/форма **Вид знания**.  Добавить логический реквизит/поле "Наличие -источника"

**Comment by breduin** [comment]
не очень понимаю эту конструкццию. А кто будет устанавливать логические значения в поля  "Наличие автора" и "Наличие -источника" ?

**Comment by lvb555** [comment]
Только тот, кто может создавать/редактировать записи справочников "Виды знаний" и "Виды связей", т.е. админ

**Comment by Intey** [comment]
Я честно говоря не понимаю сути задачи. 
Какой результат мы хотим получить? 
Текущее описание детализирует "как" реализовать, но не "что" нужно. Из заголовка могу сделалась вывод, что нужен механизм(форма, страница) с помощью которого пользователь сможет создать знание.

**Comment by lvb555** [comment]
### Замечания
  **Замечания носят чисто филологический характер**
- [ ] Текст "Для данного вида знаний поле источник является обязательным!"  заменить на "Для записей данного вида знаний поле "Источник" является обязательным!".
- [ ] Текст "Для данного вида знаний поле автор является обязательным!"  заменить на "Для записей данного вида знаний поле "Автор" является обязательным!"
.

**Comment by lvb555** [comment]
Задача завершена!
