### ISSUE TITLE
!!! Сведения об авторе

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#44]
- [x] В модель Автор добавить текстовый реквизит Сведения подобен реквизиту "Содержание"в Знании.
- [x] Админка. В форму Автор добавить **необязательное** текстовое поле Сведения
- [x] Админка. Форма **Автор** Поле **Сведения об авторе** подключить к CKEditor.
- [x] На страницу Автор добавить поле "Сведения"
- [x] На странице Знание значение поля Автор сделать ссылкой на страницу Автор при условии, что поле "Сведения" не пусто.

**Comment by breduin** [comment]
а фото автора не нужно?

**Comment by lvb555** [comment]
Ну, в принципе, конечно желательно, но я исходил из минимизации трудозатрат - ссылку на фото при необходимости можно вставить в поле "Сведения".

**Comment by breduin** [comment]
"На страницу Автор добавить поле" - про какую страницу речь? Ссылку, если можно, для примера.

**Comment by lvb555** [comment]
Я имел ввиду страницу просмотра "Автор", открываемую по ссылке на странице Знание - (как сказано в следующем задании). .  .
Спасибо за поле "Фото"!
Если создание ссылки относится к frontend, тогда делать не нужно.

**Comment by breduin** [comment]
сделал, проверьте. 
Алгоритм несколько иной: ссылка на автора со страницы просмотра Знания присутствует всегда. На странице просмотра Автора всегда есть его имя. Остальное - при наличии.

**Comment by lvb555** [comment]
Работает правильно. Спасибо за CKEditor.

Вообще, как-то выстраивается система, хорошеет в структурно-информационном аспекте. Спасибо!
