### ISSUE TITLE
Ф - Верстка  страницы "Знание" (1-я часть)

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#445]
- [ ] Верстка страницы "Знание" сайта, согласно макета:  https://www.figma.com/file/aw2bMraplkaoFdi0E4Cqjt/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9?node-id=642%3A2034&t=wOwNF0Ql5pgkwcMb-1

**Comment by goregora** [comment]
Андрей, доброго времени суток!
Насколько я знаю, у вас уже заключительная стадия разработки по данной задаче. 
Подскажите, пожалуйста, когда ориентировочно планируете полностью завершить? Интересуюсь, т.к. я буду заниматься версткой второй части страницы.
