### ISSUE TITLE
!! Ckeditor: интеграция  с  Админкой и настройка

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#46]
Админка. Страница Знание.  Поле "Содержание"
Необходимость в редактировании текста в этом поле:  переход на новую строку, выделение жирным шрифтом, возможно управление размером и цветом шрифта.

**Comment by breduin** [comment]
сделал, проверьте
http://derzn.ru/znanie/76

**Comment by lvb555** [comment]
Олег Сергеевич,  это превзошло все мои ожидания!  Чудо, как здорово! Спасибо!
