### ISSUE TITLE
!!! Проблема. Просмотр знания. Галерея фото

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#47]
Если Выдача фото производится не в одну, а в две строки, то  они как бы слипаются.  
Нужна пустая строка между этими строками с фото. В примере (см. присоединенный файл) 4фото лежат в 1-й строке, а 5-е фото во 2-й строке.
![Screenshot_1](https://user-images.githubusercontent.com/83456540/121410758-97c6bd80-c96b-11eb-8763-865f6de0968a.png)

**Comment by breduin** [comment]
сделал, проверьте.

Такие действия (позиционирование элементов на странице и их внешний вид) относятся к вёрстке (front-end), я ей, вообще говоря, не занимаюсь, у меня back-end.

**Comment by lvb555** [comment]
Да-да, я понимаю, back-end и front-end.

Спасибо.
