### ISSUE TITLE
!!! Изменить дату создания на дату редактирования знания

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#48]
- [ ] Админка. Форма создания/редактирования знания. Изменить дату создания на дату редактирования знания.
- [ ] Админка. Страница "Знания" (Список знаний).  В разделе "Фильтр" заголовок "Дата создания" заменить на "Дата редактирования".

**Comment by breduin** [comment]
такого поля, "дата редактирования", в модели нет, только дата создания. Могу добавить такое поле. Добавить?

**Comment by lvb555** [comment]
Да, тогда добавить.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Работает. Спасибо.
