### ISSUE TITLE
!! Админка. Фильтрация выпадающего списка поля "Автор"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#50]
- [ ] Админка. Окно ввода / редактирования "Знание". Поле "Автор".  Фильтрация элементов списка после ввода буквы.
- [ ] Админка. Окно ввода / редактирования "Связь". Поле "Автор". Фильтрация элементов списка после ввода буквы.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Работает.
