### ISSUE TITLE
!! Админка. Авторы.  Создать новое поле "Вид автора"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#51]
- [x]  Создать новую сущность "Виды авторов"
- [x] Модель "Автор". Добавить новый реквизит "Вид автора" - указатель на сущность "Виды авторов" 
- [x] Админка. Форма "Автор". Добавить новое поле "Вид автора"

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Отлично!  Спасибо, Олег.
