### ISSUE TITLE
! В меню сайта вставить пункт "Теги"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#52]
- [ ] В меню сайта между пунктами "Авторы" и "Панель управления" вставить пункт "Теги" - ссылку на страницу "Теги".
- [ ] Страница "Теги" содержит:
       - меню сайта
       - заголовок "Теги"
       - список меток - ссылок на списки знаний, их -содержащих (как ссылка у метки в просмотре знания).

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Спасибо.
