### ISSUE TITLE
Ф - Создание дизайна страниц с деревьями

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#528]
На портале "Дерево знаний" есть много страниц, где знания представляются в форме дерева, используя при этом иерархическую таблицу "Категории".  
### Страница "Дерево знаний"
![image](https://user-images.githubusercontent.com/83456540/218300960-707b5967-82cb-4e63-ac13-01113df73deb.png)
Дерево образовано только категориями и знаниями, прикрепленными непосредственно к категориям.  При этом знания могут прикрепляться к категориям любого уровня, а не только последнего.
![image](https://user-images.githubusercontent.com/83456540/218301384-59d870de-16b7-4f8d-bede-e7a7ee16dae8.png)
- [ ]  Создать дизайн страницы "Дерево знаний"

### Страницы для представления отфильтрованных знаний
На таких страницах деревья образованы как категориями, так и знаниями, через связи (аргументы и т.д.) образующими иерархическую структуру.  В дизайне страницы "Знание" дерево категорий и дерево, собственно, знаний выступают, как отдельные объекты, а здесь это одно, единое целое, в котором, видимо, будет присутствовать стилистика тех деревьев..
  **Страница "Авторы"**
На страницы "Авторы" мы выбираем нужного автора.  Страница выглядит так: 
![image](https://user-images.githubusercontent.com/83456540/218302244-5d99979b-181d-4081-a429-30255d3beb1f.png)
- [ ]  Создать дизайн страницы "Авторы"
  **Страница "Автор"**
Сейчас страница выглядит так:
![image](https://user-images.githubusercontent.com/83456540/218301916-edd240f6-759a-4197-94a4-e7e23b06c2c7.png)
Необходимо  создать дерево из категорий и знаний.  Вершины-знания в этом дереве двух типов:  1) найденные знания этой страницы и не найденные знания, которые помечают путь в иерархии от найденного знания к категории.  Типы знаний, видимо, надо различать цветом шрифта или как-то иначе.  При этом, наверное, нужна легенда, объясняющая как эти типы различаются?
- [ ]  Создать дизайн страницы "Автор"

**Comment by lvb555** [comment]
### Важное изменение
Уже создан модуль построения полного дерева, т.е. дерева категорий и знаний.  Этот модуль будет использовать почти на всех страницах портала, и в том числе на странице "Дерево знаний".  Поэтому в этом заказе задание 1 и задание 3 очень схожи.  Поэтому нужен некий универсальный шаблон, где есть:
-  Заголовок с хлебными крошками
-  Дерево знаний (категории и знания)
-  Возможно блок с легендой в правом нижнем углу.

**Comment by UnicornChris** [comment]
Ссылка на макет: https://www.figma.com/file/aw2bMraplkaoFdi0E4Cqjt/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9?node-id=1504%3A6959&t=9h7CqC9id8Ca9ugG-1
