### ISSUE TITLE
!! Проблема на странице "Список знаний", -содержащих эту метку

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#55]
Сейчас в окне **"Список знаний"** выдается в виде двухуровневого списка: "Категория - Знание.

- [x] Проблема в том, что в каких-то ситуациях не происходит группирования знаний по категориям.  Смотрите [пример](http://derzn.ru/drevo/label/3) 
- [x] Уж заодно, вставить заголовок на страницу - саму метку, по которой построен список знаний. 
- [ ]  Уж заодно, вопрос-пожелание:  можно вставить логический параметр:  "Основное знание"  По умолчанию (false) берутся все знания, если True - только знания, у которых поле "Категория" - пусто? Список знаний фильтруется и с использованием этого параметра.

**Comment by breduin** [comment]
сделал, проверьте. 
Третий пункт оформите отдельной задачей.

**Comment by lvb555** [comment]
Работает. Спасибо.
