### ISSUE TITLE
!! Ф - Модификация страницы "Автор"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#56]
На странице "Автор"  показывать список ВСЕХ  знаний этого автора.  Автором базового знаний может быть любой автор.   Базовое знание может быть как основным, так и дополнительным.
### Необходимые операции:

- [x]  поместить заголовок "Список знаний"
- [x]  вставить логический параметр: "Основное знание" По умолчанию (false) берутся все знания, если True - только знания, у которых поле "Категория" - пусто.
- [x] вставить двухуровневый список знаний автора: "Категория - Знание", отфильтрованный с учетом этого параметра.  Определение категории знания:
-  для основного знания категория определена в поле "Категория" этого знания
- для дополнительного знания необходимо, используя соответствующую запись "связь" добраться до основного знания и через него определить категорию, 
- [x]  Цвет шрифта знания зависит от того, является оно основным или дополнительным
-  Основное знание выдается обычным синим цветом.
-  Дополнительное знание выдается красным цветом.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Проблема: Сейчас берутся дополнительные знания только 1-го уровня, т.е. знания, у которых базовые знания являются основными.  Но, дополнительные знания могут иметь неограниченную глубину по уровням связанности.  Или берутся дополнительные знания автора, связанные с основным знанием этого же автора?  Что не есть правильно, 

В моем контенте для этого лучше всего подходит группа "Аграрная реформа Столыпина": Наука-История-История России-Аграрная реформа.  Там все знания одного автора - Шубина.

**Comment by breduin** [comment]
`Сейчас берутся дополнительные знания только 1-го уровня, т.е. знания, у которых базовые знания являются основными. `
да, в соответствии с текстом: "вставить двухуровневый список знаний автора: "Категория - Знание".

`берутся дополнительные знания автора, связанные с основным знанием этого же автора?`
да. Потому что в задании указано "добавить на страницу список знаний, автором которых он является"

Переформулируйте задание.

**Comment by lvb555** [comment]
Я переформулировал задачу, отредактировав основной комментарий.

**Comment by breduin** [comment]
`список ВСЕХ знаний этого автора`
т.е., не учитывать статус опубликования is_published? И статус категории is_published тоже не учитывать?

`Базовое знание может быть как основным, так и дополнительным.`
дайте определение базового знания, лучше в глоссарии.

**Comment by lvb555** [comment]
Конечно же учитывать, поскольку это общие правила для любых публикаций.
Под словом ВСЕХ, я понимал, что это для всех знаний (основных и дополнительных) и не зависит от автора базового знания.
