### ISSUE TITLE
!! Ф - Модификация страницы "Авторы"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#57]
Сейчас на странице выдается полный список авторов.  Предлагается фильтрация этого списка по выбранному здесь значению -параметра "Вид автора"

При открытии окна, как и сейчас, выдается полный список авторов.
При выборе значения параметра "Вид автора" происходит обновление списка - фильтрация по этому значению.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Фильтрация работает корректно.
