### ISSUE TITLE
Ф- Создание и модификация макетов дизайна разделов "Авторы" и "Теги"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#575]
- [x]  Разработка макетов страниц "Список знаний автора"  и "Список знаний тега"
- [x]  Разработка макета страницы "Теги"
- [x]  Модификация страниц раздела "Оценка знаний"

**Comment by UnicornChris** [comment]
Ссылка на макет: https://www.figma.com/file/aw2bMraplkaoFdi0E4Cqjt/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9?node-id=1504%3A6959&t=GQIpss73NNxhPPHd-1
