### ISSUE TITLE
! Ф - Система аутентификации пользователя.  Профиль пользователя

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#59]
Кнопку "Войти" разместить как элемент меню, крайний справа.  

### Профиль содержит блоки информации:

- **Личные данные:**
     1. Логин
     2. Пароль
     3.  Фамилия - Не обязательно
     4. Имя - Не обязательно
     5. Отчество - Не обязательно
     4. E-mail
     5. Пол - Не обязательно
     6. Дата рождения - Не обязательно
     7. Аватар - Не обязательно

**Comment by lvb555** [comment]
Валентин, поскольку у тебя уже есть -блоки авторизации/регистрации на твоем сайте [http://5.63.155.210/](url) , то я лишь укажу некоторые изменения и -добавления, отталкиваясь от твоего сайта:
1.  Нужные реквизиты аккаунта указаны в этой задаче
2.  Обработка ситуации по ссылке "Забыли пароль?".   У тебя она, видимо, не работает.
3.  Расширить возможность авторизации через другие соцсети:  фэйсбук, твиттер, Одноклассники - у тебя только "В контакте"

**Comment by Valentin-Butorin** [comment]
Спасибо. На данный момент осталось только реализовать авторизацию через соц. сети.

**Comment by lvb555** [comment]
### Тестирование на тестовом сайте.
- [x]  Создание профиля. Поле "Аватар".  Если слишком большой размер файла (у меня был более 1mb) выдает системную ошибку. Можно уведомить пользователя о максимально допустимом размере фото? 
- [x]  **_Проблема:_** Редактирование профиля. Поля "Отчество", "Пол", "Дата рождения", "Аватар" почему-то не сохраняются.
- [x]  Создание профиля. Поле "Дата рождения".  Хорошо бы подвесить календарь для ввода даты.

**Comment by lvb555** [comment]
Восстановление -пароля.  После перехода по ссылке из письма -возникает ошибка сервера 500.

**Comment by lvb555** [comment]
При вводе пароля обычно выдаются звездочки, но на некоторых сайтах есть пиктограмма **глаз** - для выбора режима видимости вводимого значения. Принцип "включен/выключен".

Может нам такое сделать.  На Ваше усмотрение.  В противном случае напишу задачку на будущее.

**Comment by Valentin-Butorin** [comment]
Изменения #160:

- Реализована кастомная модель пользователя с уникальным полем адреса эл. почты.
- Ограничен размер загружаемого аватара (1 МБ) с выводом сообщения об ошибке.
- Добавлены функции отображения скрытых паролей.
- Изменено поле ввода даты рождения с возможностью выбора через календарь.
- Обработана ситуация с отсутствующим в БД адресом эл. почты при восстановлении пароля.
