### ISSUE TITLE
! Админка. Фильтрация выпадающего списка. "Знание" - "Категория"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#6]
Админка. Окно ввода / редактирования "Знание". Поле "Категория". Выпадающий список

Фильтрация элементов списка после ввода буквы.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Можно при фильтрации не учитывать регистр?

**Comment by breduin** [comment]
> Можно при фильтрации не учитывать регистр?

дело в том, что конструкция, которую я применил для фильтрации, уже регистронезависимая. Для меня тоже оказалось удивительным, что на сайте это не так. Выяснил, что это фича базы данных, которая сейчас у вас используется: 

> SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE.

https://www.sqlite.org/lang_expr.html
А кириллица - как раз за пределами ASCII. Т.е. **ответ на ваш вопрос - нет**, для данной базы данных. Собственно, Sqlite предназначена для предварительных разработок, ее функционал ограничен. Когда будете ставить на сайт продакшен версию, нужно будет перейти на MySQL (или Postgres), там фильтрация будет работать нормально.
