### ISSUE TITLE
Ф- Разработка дизайна страниц "Помощь", "Глоссарий", "Разработчики" 

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#600]
- [x] Создание макетов дизайна указанных страниц.

**Comment by UnicornChris** [comment]
https://www.figma.com/file/aw2bMraplkaoFdi0E4Cqjt/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9?type=design&node-id=2118%3A22957&t=1paphlmOsANF9RUZ-1
