### ISSUE TITLE
!! Ф - Модификация страницы "Метка", -содержащей список знаний

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#62]
- [ ]  На страницу "Метка" вставить логический параметр: "Основное знание" По умолчанию (false) берутся все знания, если True - только знания, у которых поле "Категория" - не пусто.
- [ ]  Фильтрацию знаний проводить с учетом этого -параметра.
- [ ]  Определение категории знания:
-  для основного знания категория определена в поле "Категория" этого знания
- для дополнительного знания необходимо, используя соответствующую (этому связанному знанию) запись -"связь" -добраться до основного знания и через него определить категорию, 
- [ ]  Цвет шрифта знания зависит от того, является оно основным или дополнительным
-  Основное знание выдается обычным синим цветом.
-  Дополнительное знание выдается красным цветом.
- [ ]  Каждый элемент списка содержит графы "Тема", "Автор", "Вид знания", для дополнительных знаний "Вид связи" и "Дата создания".

**Comment by breduin** [comment]
уточните, куда вставить параметр: "Основное знание" ? Непосредственно на страницу? Или в модель?

**Comment by lvb555** [comment]
На страницу вставить параметр.

**Comment by breduin** [comment]
сделал, проверьте.
Сделано так же, как и с Авторами, код (модуль) один и тот же.

**Comment by lvb555** [comment]
Проблема:  В рамках категории есть несколько дополнительных знаний, но нет -ни одного основного знания.  Тогда при включении режима "Основное знание" выдается  эта категория,  пустая, но выдается.

**Comment by breduin** [comment]
а как должно быть?

**Comment by lvb555** [comment]
Ну, строго говоря, этой категории в этом случае вообще не должно быть.
Но, я вдруг подумал, а, что, если это даже хорошо, что категория пустая выдается - информация дополнительная, что основных-то нет, но дополнительные знания имеются.
Все, оставляем, как есть. Проблемы нет!

Кажется, появилась новая проблема.  Знание ID-107. Это основное знание, но категория "Психология" не опубликована.  Тег - "Test".  Две проблемы:
1. У тега "Test" неверно считается число знаний. Выдается 1, должно быть 0
2. При переходе по ссылке "Test" дает ошибку сервера 500.

**Comment by breduin** [comment]
1. Всё верно, знание http://derzn.ru/drevo/znanie/107 имеет метку Test. это знание одно, выводится 1.
2. Исправил.

**Comment by lvb555** [comment]
С 1-м пунктом я что-то маху дал,  извините.  Протестировал на контенте, сделанном для теста задачи по Автору.  **Все работает отлично!**
