### ISSUE TITLE
!! Управление публикацией категории

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#63]
По аналогии со знаниями необходимо управлять публикацией категорий.
### Необходимые операции
- [x] В сущность "Категория" добавить логический реквизит "Опубликовано".
- [x] Админка В форму "Категория" добавить поле "Опубликовано". По умолчанию: не опубликовано.
- [x] Админка  На странице "Категории" -выделять цветом или шрифтом опубликованные категории.
- [x] При построении многоуровневого списка категорий -учитывать только опубликованные категории

**Comment by breduin** [comment]
сделал, проверьте.
Сейчас все категории имеют статус "неопубликованы" (т.к. это значение по умолчанию). Соотвественнно, нужно пройтись по списку категорий и отметить те, которые должны быть опубликованы.

**Comment by breduin** [comment]
неопубликованные категории - более бледный шрифт в Админке.

**Comment by breduin** [comment]
данное решение имеет ряд минусов.
Например, нужно ли учитывать, опубликована Категория или нет, при выводе связанных Знаний? При выводе списка Знаний по метке?
Т.е. при введении в сущность такого же аргумента, как и в иерхахически связанной с ней сущности возникает необходимость пересмотра всех условий вывода сущностей на, скажем, экран. Фактически, их дублирование. Это плохо масштабируемое решение.

**Comment by lvb555** [comment]
1.  Админка На странице "Категории" -сильнее как-то выделять цветом или шрифтом опубликованные категории.  Я сейчас их не разделяю совсем. Правда, у меня плохое зрение.
2. Да, к сожалению, это тот самый случай, когда некая непродуманность в постановке требует существенных доработок в уже существующем коде. Не оправдываюсь почти, но уж слишком новая технология - идем как на ощупь, как по тонкому льду. Вот, провалились немного... 
### Ответы на вопросы в предыдущем комментарии

- Вопрос: "...нужно ли учитывать, опубликована Категория или нет, при выводе связанных Знаний?".  Ответ:  при выдаче списка связанных знаний (при просмотре знания) категории не выдаются 
- Вопрос: "При выводе списка Знаний по метке?".  Ответ:  Строго говоря, да, нужно, это как раз тот печальный случай корректировки кода. Хотя, конечно, будет неформальное правило, что Знания подвязывать можно будет только к опубликованным категориям.  Выпадающий список Категорий, в принципе, тоже можно отфильтровать по опубликованным категориям?

**Comment by breduin** [comment]
1. " Ответ: при выдаче списка связанных знаний (при просмотре знания) категории не выдаются"
ответ не соответствует вопросу. Категории не выводятся, да. Но если категория не опубликована, то должны ли публиковаться Знания, которые в эту категорию входят?

2. на данный момент в коде я установил так, что если категория не опубликована, то знания из этой категории не выводятся независимо от того, опубликованы они сами или нет.

3. " Выпадающий список Категорий, в принципе, тоже можно отфильтровать по опубликованным категориям?"
можно

**Comment by lvb555** [comment]
1.  Ответ на ответ по 1-му вопросу.  Если мы не сможем "подвязывать" знания к неопубликованным категориям, то НОВЫХ таких знаний не будет.  Что касается ситуации, когда к категории уже подвязаны Знания, а мы ее делаем неопубликованной, то я сейчас буду это контролировать вручную.  Дело в том, что -предполагается в -основном односторонний процесс: НЕ ОПУБЛИКОВАНО -> ОПУБЛИКОВАНО. 
2. По пункту 3. "Фильтрацию опубликованных категорий в выпадающем списке поля "Категория" оформлять отдельной задачей?

**Comment by breduin** [comment]
1. Ответ до конца не понятен. Что конкретно делать в коде: убрать все условия проверки на опубликованность Категорий при любом выводе знаний?
2.  да, желательно.

**Comment by lvb555** [comment]
1. При выводе связанных знаний опубликованность учитывается (как это уже и сделано).
