### ISSUE TITLE
Число знаний у автора и у тега

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#64]
У элементов списка авторов и списка тегов указывать число знаний с ними связанных.

- [x] Страница "Авторы".  Рядом с именем автора в квадратных скобках указывать число знаний этого автора.
- [x] Страница "Теги".  Рядом с -названием тега в квадратных скобках указывать число знаний, -содержащих этот тег.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Проблема по п.2 "Теги": в списке тегов у элемента "Гражданская война..." стоит число 2. 
![image](https://user-images.githubusercontent.com/83456540/123649060-26737f80-d832-11eb-9f4f-c75491f811ef.png)
А на странице тега показано только 1 знание:
![image](https://user-images.githubusercontent.com/83456540/123649422-68042a80-d832-11eb-827c-f6740c8aec9b.png)

**Comment by breduin** [comment]
это как раз следствие ситуации с Категориями. Я поставил условие, что если Категория опубликована, тогда и Знание из этой категории выводить  в списке знаний. А у одного из знаний по этому тегу категория - пустая, т.е., по вашей терминологии, это основное знание. Оно под условие вывода не попадает, т.к. нет категории = нет опубликованной категории. 
А Знания считаются все, независимо от опубликованности Категорий.
Что делаем? Можно и в подсчет количества знаний включить условие опубликованности категорий. Можно убрать проверку опубликованности категорий из вывода списка связанный знаний.

**Comment by lvb555** [comment]
Понятно, Я даже задачку написал по этому поводу на ДАЛЕКУЮ перспективу.

**Comment by lvb555** [comment]
Извините, тут я немножко сплоховал.
Да, конечно же, в подсчет количества знаний включить условие опубликованности категорий.
