### ISSUE TITLE
Ф - Создание дизайна страниц раздела "Тестирование"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#643]
Этот раздел содержит несколько страниц
1. Страница "Тесты" Страница вызывается из подменю "Другое".  Это обычное наше дереве, где представлены знания вида "Тест" 
2. Страница "Тестирование по вопросу теста"
3. Страница "Результаты теста"
4. Страница "Результаты тестов".  Страница вызывается в "меню профиля:  подменю  "Изучение знаний - Результаты тестов"

**Comment by UnicornChris** [comment]
https://www.figma.com/file/aw2bMraplkaoFdi0E4Cqjt/%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D0%B9?type=design&node-id=2401%3A25382&mode=design&t=EP9C8R1xDs2tW8za-1

**Comment by lvb555** [comment]
### Темы для обсуждения
-  Страница "Тестирование".  Сообщение о нехватке ответов "Необходимо отметить ещё <Число ответов> ответа"я предлагаю выдавать над кнопкой "Результат" 
-  Страница "Результат  по вопросу теста".   Что если кнопки "Далее"  и "Назад" переместить вниз страницы, под список ответов и поменять их местами?.
-  Страница "Результат  по вопросу теста".  Может 
быть обводка ответов,  данных пользователем, не нужна, как дифференцирующий признак, поскольку все такие ответы уже выделены галочкой?   Если решим обводку убрать, то не забыть удалить её элемент из легенды.
