### ISSUE TITLE
! Ф - Использование знаний-вида "Ярлык"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#66]
Наше дерево знаний по сути должно быть ориентированным графом, в котором возможно наличие нескольких родителей у вершины. Но, нам нужна прозрачность дерева, когда мы можем однозначно восстановить путь к любому знанию.
Проблема решается с помощью знания системного вида "Ярлык" -  как бы отражения некоторого знания, с которым он соединен связью системного вида "Ярлык".  Такое знание (далее - **ярлык**)  - знание, при просмотре которого информация наследуется из другого  знания, ярлыком которого он является.  Таким образом. ярлык - своего рода, экземпляр какого-то знания, при изменении которого, возможно, динамично изменится и сам ярлык.  Сразу отметим, что ярлык не является полной копией своего знания.  Ниже будут приведены правила отображения, т.е. -наследования реквизитов ярлыком.

Суть ярлыка показана на схеме.
![Использование ярлыков знаний в дереве](https://user-images.githubusercontent.com/83456540/146379222-edcf8924-25f5-4f9f-b3d1-9262f505b761.png)
По логике контента два знания **Знание-А** и **Знание-Б** должны быть связаны со **Знание-В**.  Но в базе данных мы этого сделать не можем и тогда мы создаем  **ярлык**, т.е. **Знание-В (ярлык)**.  Но, **Знание-В** имеет связанное знание   **Знание-Г**.  Связать **ярлык** с ним в базе данных мы не можем,  но можно создать его ярлык и связать его с первым ярлыком. Таким образом, при необходимости создания ярлыка знания нужно создать ярлыки всех потомков и связи между ними.  Поддереву знания будет соответствовать аналогичное поддерево ярлыков.  На схеме видно, что у нашего **1-го ярлыка**   есть и своя, уникальная связь с **Знание-Е**. 

Ярлык создается вручную либо автоматически.
### Создание ярлыка в Админке (ручной способ).
Для этого на странице "Знание" нужна кнопка-ссылка "Создание ярлыка". Порядок создания:
   1. Создается новое знание
      - Поле "Вид знания" = "Ярлык"
      -  Поле "Тема"= Поле "Тема" (Связанного знания) + " #" + str(<Номер ярлыка>)
          Номер ярлыка создается подобно ID записи в БД.  Поле можно изменить.
   2. Создается новая связь
      - Поле "Базовое знание" указывает на созданную запись-ярлык
      - Поле "Вид связи" = "Ярлык" 
      - Поле "Связанное знание" указывает на то знание, ярлыком которого наш ярлык будет. 
          Ограничение:  Это знание не может иметь _Вид знания_ "Ярлык"  
   3. Открытие окна редактирования ярлыка
      - Поле "Тема" - обязательное, уникальное поле.
      Нюанс редактирования ярлыка:
          -  Модификация блока обработки события "Сохранение знания": Требования обязательности полей (кроме поля "Тема") -отменяются для знаний вида "Ярлык".

### Создание ярлыков в Админке при сохранении Связи.  
 Мы создали (изменили) связь.  При обработке события "Сохранить Связь" обнаруживается, что связь с таким связанным знанием уже есть.  Тогда сервис предлагает создать ярлык связанного знания.  Если мы согласны тогда:
    1.  Создается новое знание
        1.1.  Поле "Тема"= Поле "Тема" (Связанного знания) + " #" + str(<Номер ярлыка>)
        1.2.  Поле "Вид знания"= "Ярлык"
    2.  Создание новой связи:
         2.1. Поле "Базовое знание" указывает на созданную запись-ярлык
         2.2. Поле "Вид связи" = "Ярлык" 
         2.3. Поле "Связанное знание" указывает на то знание, ярлыком которого наш ярлык будет. 
    3.  Открывается окно редактирования ярлыка.
    4 . **Создание ярлыков и новых связей для всех потомков текущего знания.**  Итерационная процедура.

### Использование ярлыков
Пока известно два случая использования ярлыков:
  1. при просмотре  самого ярлыка.  Применяются правила наследования.
  2. для построения дерева предков при просмотре знания.  Используется поле "Тема". 

### Правила наследования
-  наследуются все связи знания,  при этом ярлык может иметь свои собственные связи.
-   наследование не происходит для следующих полей:  
    1. поле "Тема"
    2. поле "Категория"
-   Для следующих полей наследование происходит только тогда, когда оно пустое в ярлыке:
      1. поле "Вид знания"
      2. поле "Содержание"
      3. поле "Источник"
      4. поле "Комментарий к источнику"
      5. поле "Автор"
      6. поле "Порядок"
      6. поле "Опубликовано?"
-   Для следующих полей наследование происходит - информация добавляется к информации самого  ярлыка:
      1. поле "Метки"
      2. поле "Фото"

**Comment by breduin** [comment]
прошу создать соответствующие Вид знания и Вид связи в текущей базе данных, я буду использовать эти названия.

**Comment by lvb555** [comment]
Проблема множественности родителей знаний решена.  Поэтому в ярлыках нет нужды.
