### ISSUE TITLE
Ф - Поиск знаний

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#67]
На странице "Дерево" поместить кнопку "Поиск знаний" для перехода на страницу "Поиск знаний" с набором условий поиска.  Результаты поиска выдаются на специальной странице "Результаты поиска знаний".  Поиск проводится по таблице "Знания".
![image](https://user-images.githubusercontent.com/83456540/123539617-555ef800-d743-11eb-86fd-6eabeaef65a6.png) 
### При поиске действуют правила:
1. Поиск по шаблону проводится по двум текстовым полям "Тема" и "Содержание". 
2. Поиск по условию "Вид знания" проводится по полю "Вид знания" (указатель на таблицу " Виды знания"). 
3. Поиск по условию "Автор" проводится по полю "Автор" (указатель на таблицу "Авторы"). 
4. Поиск по условию "Источник" проводится по текстовому полю "Источник".
5. Поиск по условию "Вид связи" проводится по полю "Вид связи" (указатель на таблицу "Виды связи"). 
6. В зависимости от наличия условий необходимы два алгоритма поиска:
    6.1. Если условие "Вид связи" пусто, тогда обычная процедура поиска по условиям.
    6.2. Если условие "Вид связи" не пусто, тогда двухэтапная процедура:
          1. Фильтрация связей - записей таблицы "Связи" по условию  "Вид связи" с результатом в форме списка связанных знаний (поле "Связанное знание").
           2. Фильтрация полученного списка знаний по всем другим условиям
7. Результаты поиска нужно представлять в форме двухуровневого списка "Категория - Знание" подобно тому, как это сделано на страницах "Авторы", "Теги"..

**Comment by breduin** [comment]
можно -объединить. Или поиск в боковую колонку поставить.

**Comment by lvb555** [comment]
Вот-вот в боковую колонку было бы хорошо.

**Comment by nikdevel** [comment]
А почему бы к "Шаблон поиска" не прикрутить поисковый движок? Elastic или Sphinxsearch?

**Comment by lvb555** [comment]
### Дополнения к задаче

- [x] Шаблон поиска используется для поиска по следующим полям записей:
- Тема
- Содержание
- Источник
- Комментарий к источнику
- [x] Проводится поиск по полям с указателями на другие таблицы:
- Вид знания
- Автор
- Вид связи 
- [ ] Результаты запроса представляются в виде списков блоков информации найденных записей:
- 1-й столбец:  Тема  (ссылка на страницу "Знание".
- 2-й столбец:  Содержание
- 3-й столбец:  информация таких полей
  -  Автор
  - Вид знания
   - Вид связи  (выдается только если знание является связанным)

**Comment by lvb555** [comment]
Проверка связи

**Comment by lvb555** [comment]
### Еще пожелания:
- [x]  Название условия "Тип связи"  заменить на  "Вид связи".
- [x]   Хорошо бы сортировать выпадающие списки по алфавиту (как исходные, так и после фильтрации):  Вид Знания, Категория, Автор, Вид связи.
**Обсуждение:**  А что, если весь блок информации (Вид Знания, Категория, Автор, Вид связи.) выдавать всплывающим комментарием при наведении на  "!", стоящий в конце Темы знания?

**Comment by DemidovEvg** [comment]
>   **Обсуждение:**  А что, если весь блок информации (Вид Знания, Категория, Автор, Вид связи.) выдавать всплывающим комментарием при наведении на  "!", стоящий в конце Темы знания?
- Мне кажется что будет не очень удобно для пользователя. Например он искал в общем поле "Вторая мировая", а после бежит глазами по списку и хочет найти конкретного автора, ему тогда придется наводить на все посты мышкой.
=========================
- И по поводу "Вид связи", с ним надо подумать. Мы получается ищем связанные знания, у каждого связанного знания может быть несколько связей, мы будет выдавать их списком в результате? Или может их тогда не выдавать? Или выдавать только когда искали по конкретному виду связи, но если мы по нему искали, есть ли смысл тогда выдавать?
- И есть еще момент по алгоритму поиска. Давать ли возможность искать например по Виду знания вбив только например "вопрос"  и тогда он будет искать по видам из перечня ['Вопрос', 'Главный вопрос', 'вопрос повтор']. Сейчас я сделал что так искать будет.

**Comment by lvb555** [comment]
Результаты запроса.  Поле "Содержание"
Изменить размер выдаваемого текста с 50 на 30 слов.

**Comment by lvb555** [comment]
- [x] Если реквизит "Вид связи пустой, то не выдавать эту строчку "Вид связи"
- [x] Если реквизит "Категория пустой, то не выдавать эту строчку "Категория"
- [x] Результаты для экономии места помещать двумя столбцами:
1. Тема и Содержание
2. Все остальные реквизиты
Пропорции ширин столбцов можно оставить такие же, как сейчас задается ширина реквизита "Тема".
- [x] Результаты.  Название реквизита "Категория знания" заменить на "Категория".
- [x] Тексты подсказок в полях выбора:
- **Вид знания**  - "Выберите вид знания"
- **Категория**   - "Выберите категорию"
- **Автор**  - "Выберите автора"
- **Вид связи**   - "Выберите ид связи"

**На обсуждение**:  Хорошо бы сделать, чтобы в выпадающем списке Видов связей вместо **Событи [е, я]**  стояло **Событие**, т.е. взять подстроку до " [" и добавить к ней 1-й символ после "[".

**Comment by lvb555** [comment]
Великолепная работа!
