### ISSUE TITLE
!! Метазнания и знания. Модификация сущности "Виды знания"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#69]
По мере развития концепции Дерева знаний появилась необходимость разделять все знания на две группы: знания для пользователя и системные знания, к последним относятся знания вида "Вариант" и "Ярлык", а в будущем добавятся системные знания для знания для описания структуры и содержания таблиц сравнения и просто таблиц.  По аналогии "Метаданные-данные", у нас будут "Метазнания (системные знания) - знания".
### Необходимые операции

- [ ] В сущность  "Вид знания"  добавить логический реквизит "Системный".
- [ ] Админка  В форму "Вид знания" добавить поле "Системный". Значение по умолчанию (false) - не системный

**Comment by lvb555** [comment]
1. Я все задания по скрыванию системных знаний для Публики перенес в отдельную задачу.  Метка "Аутентификация" здесь потеряла смысл.
2. Указал задачу как приоритетную.

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Спасибо, все хорошо!
