### ISSUE TITLE
Реквизит "Публикация знания": изменение модели и использование

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#7]
1. Модель "Знание". Добавить булевский реквизит "Публикация".  По умолчанию - не опубликован.
2. Знание включается в список  знаний (просмотр категории)) и список связанных знаний (просмотр базового знания) только, если этот реквизит равен ИСТИНА.

**Comment by breduin** [comment]
сделал, проверьте. Если ок, то нажмите Close issue.

**Comment by lvb555** [comment]
ок
