### ISSUE TITLE
!! Метасвязи и связи. Модификация сущности "Виды связей"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#76]
По мере развития концепции Дерева знаний -появилась необходимость разделять -все связи на две группы: -связи для пользователя и -системные связи, к последним -относятся, например,  знания вида  "Ярлык", а в будущем добавятся и другие системные связи  для описания -структуры и -содержания таблиц сравнения и просто таблиц.  По аналогии "Метаданные-данные", у нас будут "Метасвязи (системные связи) - связи".
### Необходимые операции

- [ ] В сущность  "Вид связи"  добавить логический реквизит "Системный".
- [ ] Админка  В форму "Вид связи" добавить поле "Системный". Значение по умолчанию (false) - не системный

**Comment by breduin** [comment]
сделал, проверьте
