### ISSUE TITLE
Ф - Переработка страницы "Просмотр знания вида "Таблица"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#790]
Сложное знание этого вида содержит таблицу знаний.  Эта задача была реализована ранее, смотрите постановку задачи #72

Но обнаружилась серьезная проблема.  Сейчас при построении таблицы используется допущение, что одно и то же знание не может содержаться в двух и более ячейках таблиц (ы).  Это абсолютно неверное допущение.

Поэтому нужно устранить эту проблему.  В вышеупомянутой задаче 72 был приведен алгоритм такого построения, но реализовано было иначе.

**Comment by Xbro1305** [comment]
здравствуйте, могу сделать быстро надежно и дешево, обращайтесь в телеграм @Sh4rifoff

**Comment by WebDevLap** [comment]
Здраствуйте, я могу исправить данную проблему. Мой телеграм - @AkhmedFr
