### ISSUE TITLE
При просмотре знания  не выводить необязательные, пустые поля

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#8]
Просмотр знания.
Для всех необязательных полей не выводить название поля и значение "None":
1. Поле "Категория" 
2. Поле "Содержание"
2.  Поле "Источник"
3.  Поле "Комментарий к источнику"

**Comment by breduin** [comment]
а что выводить? Можно пустую строку ('') или заданное выражение, напр. 'не указано'.

**Comment by lvb555** [comment]
Наверное, лучше пустую строку

**Comment by breduin** [comment]
сделал, проверьте. Если ок, то нажмите Close issue.
