### ISSUE TITLE
Создание глоссария

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#83]
Новизна проекта влечет появление новых терминов, еще неизвестных пользователям. Поэтому требуется создание глоссария - сущности, содержащих два реквизита: название и описание термина.
.

**Comment by lvb555** [comment]
Раздел "Глоссарий". 
1.  При создании списка терминов сейчас не работает реквизит "Опубликовано".
2. Нужно между терминами сделать пустую строку, так как описание термина может быть многострочным.  Например, термин "Знание"

**Comment by breduin** [comment]
сделал

**Comment by lvb555** [comment]
В Админке в таблице "Термины глоссария" сделать возможным форматирование поля "Описание", как поле "Содержание" в таблице "Знания".  Тогда при указании термина я бы мог его выделять в тексте..
