### ISSUE TITLE
Т - Переработка раздела "Работа со знаниями вида "Таблица"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#838]
Кардинально изменится способ описания сложного знания вида "Таблица".   
 Если ранее для описания таких знаний использовали системные знания и связи, то теперь описания будут храниться в формате json в полях «Метаинформация» в знаниях и связях. 

Необходимо переработать коды трех страниц:
1. "Конструктор табличных знаний"
2. "Наполнение таблиц"
3. "Просмотр табличных знаний"

**Comment by lvb555** [comment]
### Замечания и дополнения
**Страница "Конструктор таблиц**

- [x]  Проблема.  Таблица "Метатаблица-1"  построена (строки и столбцы есть), но при открытии (Тема знания) говорит,  
![image](https://github.com/lvb555/derzn/assets/83456540/cc47bbd3-4c47-4258-8193-67cd36f975f9)


**Страница "Конструктор таблицы"**

- [x]  Создание строки/столбца.  Может упростить цепочку действий - по нажатию "+" сразу открывать форму создания?
- [x]  По кнопке "Сохранить" сейчас сразу закрывается страница конструктора.  Хорошо бы её не закрывать при этом.
- [x]  Может быть добавить кнопку "Просмотр", чтобы посмотреть создаваемую конструкцию вживую, как таблицу?
- [ ]  На проекте есть правило, что все страницы, открываемые в профиле, содержат шапку профиля.  
![image](https://github.com/lvb555/derzn/assets/83456540/2be4a324-f676-48ff-bf90-0e2dc55f5708)

- [ ]  Форма создания знания.  Поле "Категория". Нужно снять требование обязательного заполнения.

**Comment by RomanBorovskiy** [comment]
1. Не смог повторить, в открытой таблице структура есть
2.  Можно и так, показалось так удобнее - сначала создать нужное количество колонок/столбцов, потом их называть
3. +
4. +/- Сейчас рендер таблицы происходит на сервере, то есть таблицу надо сначала сохранить. 
Можно отобразить структуру тааблицы на стороне клиента с помощью JS, возможно она будет отличаться по виду от того, что сервер возвращает
5. - 1).Страницы (диалоги) открываются в конструкторе таблиц/наполнении таблиц, которые не содержат шапку профиля, соответственно,  не содержат шапки профиля. 2) Шапка профиля заберет половину экрана, надо будет скролить вниз для работы

**Comment by RomanBorovskiy** [comment]
` Проблема. Таблица "Метатаблица-1" построена (строки и столбцы есть), но при открытии (Тема знания) говорит,`
Точно, нажатие не проверил, а там старый код стоит и проверяет на старые таблицы. Уберу его вообще.
Отдельно как знание можно открыть https://test.derzn.ru/drevo/znanie/1324

**Comment by RomanBorovskiy** [comment]
` Форма создания знания. Поле "Категория". Нужно снять требование обязательного заполнения.`
При заполнении таблицы? Тогда знание будет вне категории?
