### ISSUE TITLE
Алгоритм оценки знания.  Вопросы и предложения

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#895]
- [ ]  Проблема.  Ситуация отсутствия доказательной базы.  В этом случае параметр "Оценка доказательной базы"  должен быть "Нет оценки"№.  Сейчас это не так, он почему-то принимает значение "Полностью согласен".    Пример:  
![image](https://github.com/lvb555/derzn/assets/83456540/ea2c8cfe-c48e-42d8-81e9-7640dab2435a)  
Кстати, есть вопросы по этому скрину.
1. Почему значение параметра "Моя оценка" выдается на белом фоне?

- [ ]  В случае значения "Нет оценки"  не выдавать числовое значение. 

Вопрос.  Почему так здесь считается итоговая оценка, когда есть Моя оценка?  
![image](https://github.com/lvb555/derzn/assets/83456540/460ceb5a-b037-433b-8823-c4dad7c48caf)

### Переход на страницу оценки знания - отца

На странице в таблице Доказательной базы есть ссылка для перехода на страницу Оценки дочернего знания, т.е. Движение вниз.
- [ ] Но теперь нужно и движение вверх, т.е. на страницу оценки знания-отца.  Поэтому нужно справа от кнопки "Вернуться на страницу знания" поместить кнопку "Оценка знания - отца".  При этом нужно учитывать, что у знания может быть несколько отцов. или не быть отца  Поэтому  
- [ ]  Кнопка "ПЕрейти ... отца"  появляется только при наличии хотя бы одного отца
- [ ]  При наличии нескольких отцов нужно предлагать поле выбора со списком этих отцов.

**Comment by RomanBorovskiy** [comment]
Проблема. Ситуация отсутствия доказательной базы. В этом случае параметр "Оценка доказательной базы" должен быть "Нет оценки"№. Сейчас это не так, он почему-то принимает значение "Полностью согласен". 
Если нет доказательной базы - это простое знание и мы ему верим. Если его оценка - "нет оценки" (то есть 0), то какая оценка будет у знания, что опирается на такое простое знание?

1. Почему значение параметра "Моя оценка" выдается на белом фоне? 
Хороший вопрос. Либо что-то не прогрузилосось и при обновлении страницу изменится. Либо надо разбираться. 
Я открыл https://test.derzn.ru/drevo/znanie/19/grade/ - там все нормально показывает. 
https://derzn.ru/drevo/znanie/19/grade/ - тоже. 
!!Для начала надо полностью заполнить справочник шкала оценок - Я ИХ ОБНОВИЛ НА ОСНОВНОМ САЙТЕ

2. В случае значения "Нет оценки" не выдавать числовое значение
Сейчас логика такая - "Нет оценки" - это значение по умолчанию. Его нельзя выбрать из списка. Для "Нет оценки" значения числового нет.  Для "Трудно сказать" есть числовое значение 0. Оно показывается.  Убрать отображение не трудно, если требуется

3. Почему так здесь считается итоговая оценка, когда есть Моя оценка? 
 Моя оценка стоит "Нет оценки", но в справочнике стоит диапазон 2! (я уже исправил). Логика простая - если есть Моя оценка и она не 0 - итоговая оценка ровна моей оценке, иначе берем оценку доказательной базы

4. Если знание-потомок открыто в контексте рассмотрения родительского знания - то можно всегда вернуться по кнопке назад. Для случайно открытого знания искать те знания, для которых оно является потомком и узнавать их оценку - не могу представить такую ситуацию и потребность. Может для какого-то анализа может потребоваться такой инструмент, но это примерно тоже самое, что искать не ссылки на странице, а показывать ВСЕ страницы в интернете, что ссылаются на нашу страницу. Или приводить в работе не список использованной литературы, а список работ, которые ссылаются на нашу работу.

**Comment by lvb555** [comment]
### Замечания и дополнение
- [ ]  Если у знания нет доказательной базы (Вы называете его простым знанием), тогда: не нужно выдавать параметр "Оценка доказательной базы", как не имеющий смысла.

- [ ]  Таблица "Доказательная база".  Разделять каким-то образом (цветом шрифта?) знания, имеющие потомков, от простых знаний.

### Проблема расхождения одних и тех же данных на разных страницах
Вот страница оценки  знания с потомком
![image](https://github.com/lvb555/derzn/assets/83456540/dbdad8b7-21ce-40fc-ab0a-a6b687dd62cd)

А вот то же знание в таблице доказательной базы
![image](https://github.com/lvb555/derzn/assets/83456540/ad8e8182-2d5d-4008-bedc-3be1334bdcee)

**Comment by RomanBorovskiy** [comment]
Таблица "Доказательная база". Разделять каким-то образом (цветом шрифта?) знания, имеющие потомков, от простых знаний. 
они отличаются, на тех, у кого есть потомки - стоит + в иконке знания

**Comment by RomanBorovskiy** [comment]
Проблема расхождения одних и тех же данных на разных страницах
А что неправильно? При Локальной оценке так и должно быть. Если переключить на Полную оценку - будет оценка знания из всего дерева, а так получается моя оценка - Трудно сказать (значит берем оценку эксперта), оценка эксперта 1 при локальной оценке, 0,4 при Полной оценке.  Логично, что оценки знаний при локальной оценке и полной оценке отличаются.

**Comment by lvb555** [comment]
### Замечания и дополнения - 1
**Страница "Оценка знаний"**
- [ ] При отсутствии доказательной базы  текст об этом сейчас имеет фон, поэтому визуально смотрится как какая-то оценка.  Хорошо бы выдавать этот текст на белом фоне. 
![image](https://github.com/lvb555/derzn/assets/83456540/ced9d9c8-1fbe-4944-bcb2-37989f642cc3)

**Comment by lvb555** [comment]
### Страница "Мои оценки"
- [ ]  В описание вершины-знания слева добавить Вид знания, как это в основном дереве
- [ ]

**Comment by lvb555** [comment]
### Страница "Инфографика"
- [ ]  Окраска вершины-текущего довода зависит не только от вида связи с его отцом, но и от вида связи отца с дедом.
1. Если связь отца с дедом - Аргумент, то все, как сейчас, т.е. зависит от связи текущего довода с отцом 
2. Если связь отца с дедом - Контраргумент, то окраску текущего довода проводить не нужно
Вид связи текущего довода с отцом как бы переворачивается:   аргумент трактуется (окрашивается) контраргументом и наоборот.
**Иными словами  цветом "За"№ закрашивается все, что доказывает истинность текущего знания.  И наоборот**

- [ ]  Сделать название текущего знания ссылкой на его страницу "Оценка знания"
- [ ]
