### ISSUE TITLE
Ф - На -странице просмотра -знания встроить блок "Комментарии"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#9]
На странице "Просмотр -знания" добавить блок "Комментарии"..
Блок должен быть внизу страницы  перед блоком "Древовидное .представление".
Предлагается трехуровневая структура: **комментарий -> ответ -> ответ**.
Реализация блока подобна Яндекс-Дзену, но с ограничениями:
### Структура блока
1. Слово "Комментарии" и число комментариев  (Выбор режима сортировки списка не нужен. Упорядочивается по убыванию -даты-времени создания.)
2. Окно ввода "Комментировать"
3.  Список первых 3-х  комментов:
     3.1.  Аватар и логин автора комментария
     3.2.  Текст комментария
     3.3.  Кнопка "Ответить"  Пиктограмма с всплывающим сообщением "Автор 
 одобряет".  Лайки/дизлайки пока не делать.   
     3.4.  Список ответов на комментарий, упорядоченных по убыванию даты-времени:
         3.4.1.  Аватар и логин автора ответа 
         3.4.2.  Текст ответа на комментарий
         3.4.3.  Кнопка "Ответить"  Пиктограмма с всплывающим сообщением "Автор одобряет".  Лайки/дизлайки пока не делать.   
         3.4.4.  Список ответов на ответ, упорядоченных по убыванию даты-времени:
             3.4.4.1.  Аватар и логин автора ответа 
             3.4.4.2. Текст ответа на ответ.
4.  Ссылка "Еще" + <число комментариев - 3> + "комментариев", по которой выдаются все остальные комментарии.

**Comment by lvb555** [comment]
### Дополнения к задаче

- [x] Под числом комментариев сейчас -понимается число ВСЕХ -вершин дерева, что не совсем верно.  -Нужно именно число комментариев, подобно тому, как это сделано для числа ответов.
- [x] Комментарии выдаются по 3 штуки с помощью кнопки "Загрузить еще".  Нужно эту логику -перенести и на ответы.
- [x] Проблема при большом предыдущем ответе:  Ширина поля "Ответить" равна ширине поля последнего ответа.

**Comment by lvb555** [comment]
Спасибо!  Красивая работа!

**Comment by Valentin-Butorin** [comment]
@lvb555, Спасибо!
