### ISSUE TITLE
!!! Ф - Модификация страницы "Автор" - дополнение к задаче #56

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#90]
Это - дополнение к задаче [https://github.com/breduin/derzn/issues/56](url)
При поиске категории в случае дополнительного знания, т.е. при построении цепочек необходимо учитывать еще одну потенциальную возможность обрыва цепочки - 

если **связь двух  знаний цепочки не опубликована.**

**Comment by breduin** [comment]
сделал, проверьте
