### ISSUE TITLE
!!!  Админка. Модификация страницы "Знание"

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#95]
В заголовок записи добавить слева Идентификатор записи:  <Идентификатор> - <Тема>

**Comment by breduin** [comment]
сделал, проверьте

**Comment by lvb555** [comment]
Увидел!  Спасибо за ссылки на Историмю и Смотреть на сайте! 
Если  можно, то эти кнопки чуточку сдвинуть вверх на уровень заголовка "Изменить Знание" - у меня они налагаются на заголовок знания.

**Comment by breduin** [comment]
если есть возможность, пришлите скрин, как и что накладывается

**Comment by lvb555** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/83456540/134960540-a4763f9a-dbdb-4d43-b827-93343b6e0c2d.png)
