### ISSUE TITLE
!! Т - Дерево знаний. Сортировка основных знаний в категории

### ISSUE THREAD

**Issue by lvb555** [lvb555/derzn#97]
Основные знания в рамках категории должны быть отсортированы по убыванию значения поля "Порядок" сущности "Знание".

**Comment by breduin** [comment]
сделал, но проверить на сайте затруднительно, т.к. у большинства знаний атрибут Порядок не заполнен.

**Comment by lvb555** [comment]
Работает правильно. Спасибо!
